; Generated by Brainhair Compiler
bits 32

extern syscall1
extern syscall3

section .data
str_0: db "", 10, "", 0
str_1: db "Error: too many symbols", 10, "", 0
str_2: db "Error: not an ELF file: ", 0
str_3: db "", 10, "", 0
str_4: db "Error: not a relocatable file", 10, "", 0
str_5: db ".text", 0
str_6: db ".data", 0
str_7: db ".bss", 0
str_8: db ".rel.text", 0
str_9: db "_start", 0
str_10: db "Error: undefined symbol: ", 0
str_11: db "", 10, "", 0
str_12: db "Error: cannot create output file", 10, "", 0
str_13: db "bhlink - Brainhair Linker v0.1", 0
str_14: db "Usage: bhlink input.o [...] -o output", 0
str_15: db "Error: no output file specified (-o)", 10, "", 0
str_16: db "  Output: ", 0
str_17: db "  Reading ", 0
str_18: db "Error: cannot open file: ", 0
str_19: db "", 10, "", 0
str_20: db "  Symbols: ", 0
str_21: db "", 0
str_22: db "  Relocations: ", 0
str_23: db "", 0
str_24: db "  Text: ", 0
str_25: db " bytes", 0
str_26: db "  Data: ", 0
str_27: db " bytes", 0
str_28: db "  BSS: ", 0
str_29: db " bytes", 0
str_30: db "  Entry: ", 0
str_31: db "", 0
str_32: db "Done.", 0

section .bss
g_output: resb 4
g_output_len: resb 4
g_output_cap: resb 4
g_text: resb 4
g_text_len: resb 4
g_data: resb 4
g_data_len: resb 4
g_bss_len: resb 4
g_sym_names: resb 4
g_sym_name_len: resb 4
g_sym_values: resb 4
g_sym_sections: resb 4
g_sym_offsets: resb 4
g_sym_count: resb 4
g_reloc_offsets: resb 4
g_reloc_types: resb 4
g_reloc_syms: resb 4
g_reloc_count: resb 4
g_entry_point: resb 4
g_error: resb 4

section .text
global _start
global get_argc
global get_argv

section .bss
_startup_esp: resd 1

section .text

_start:
    mov [_startup_esp], esp  ; Save initial stack pointer
    call main
    ; Exit with return code from main
    mov ebx, eax  ; Exit code
    mov eax, 1    ; sys_exit
    int 0x80

; get_argc() - returns argument count
get_argc:
    mov eax, [_startup_esp]
    mov eax, [eax]  ; argc is at [esp]
    ret

; get_argv(index) - returns pointer to argument string
get_argv:
    push ebp
    mov ebp, esp
    mov eax, [_startup_esp]
    mov ecx, [ebp+8]  ; index
    lea eax, [eax + 4 + ecx*4]  ; argv[index] = esp + 4 + index*4
    mov eax, [eax]
    pop ebp
    ret
    
strlen:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start0:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end1
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start0
while_end1:
    mov eax, [ebp-4]
    jmp strlen_return
strlen_return:
    mov esp, ebp
    pop ebp
    ret
    
print:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, [ebp+8]
    push eax
    call strlen
    add esp, 4
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
print_return:
    mov esp, ebp
    pop ebp
    ret
    
print_err:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, [ebp+8]
    push eax
    call strlen
    add esp, 4
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 2
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
print_err_return:
    mov esp, ebp
    pop ebp
    ret
    
println:
    push ebp
    mov ebp, esp
    mov eax, [ebp+8]
    push eax
    call print
    add esp, 4
    mov eax, 1
    push eax
    lea eax, [rel str_0]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
println_return:
    mov esp, ebp
    pop ebp
    ret
    
print_num:
    push ebp
    mov ebp, esp
    sub esp, 24
    mov eax, 10
    mov [ebp-16], eax
    mov eax, 0
    push eax
    mov eax, 11
    mov ebx, eax
    lea eax, [ebp-12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp+8]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else3
    mov eax, 48
    push eax
    mov eax, 10
    mov ebx, eax
    lea eax, [ebp-12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 10
    mov [ebp-16], eax
    jmp endif2
else3:
    mov eax, [ebp+8]
    mov [ebp-20], eax
    mov eax, 0
    mov [ebp-24], eax
    mov eax, [ebp-20]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else5
    mov eax, 1
    mov [ebp-24], eax
    mov eax, 0
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-20], eax
    jmp endif4
else5:
endif4:
while_start6:
    mov eax, [ebp-20]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short8
    test ebx, ebx
    jz and_short8
    mov eax, 1
    jmp and_end9
and_short8:
    xor eax, eax
and_end9:
    test eax, eax
    jz while_end7
    mov eax, 48
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov eax, edx
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    lea eax, [ebp-12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-20]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov [ebp-20], eax
    mov eax, [ebp-16]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-16], eax
    jmp while_start6
while_end7:
    mov eax, [ebp-24]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else11
    mov eax, 45
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    lea eax, [ebp-12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-16]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-16], eax
    jmp endif10
else11:
endif10:
    mov eax, [ebp-16]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-16], eax
endif2:
    lea eax, [ebp-12]
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    call print
    add esp, 4
print_num_return:
    mov esp, ebp
    pop ebp
    ret
    
print_hex:
    push ebp
    mov ebp, esp
    sub esp, 28
    mov eax, 48
    push eax
    mov eax, 0
    mov ebx, eax
    lea eax, [ebp-12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 120
    push eax
    mov eax, 1
    mov ebx, eax
    lea eax, [ebp-12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 2
    mov [ebp-16], eax
while_start12:
    mov eax, [ebp-16]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end13
    mov eax, 48
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    lea eax, [ebp-12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-16]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-16], eax
    jmp while_start12
while_end13:
    mov eax, 0
    push eax
    mov eax, 10
    mov ebx, eax
    lea eax, [ebp-12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 9
    mov [ebp-20], eax
    mov eax, [ebp+8]
    mov [ebp-24], eax
while_start14:
    mov eax, [ebp-24]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short16
    test ebx, ebx
    jz and_short16
    mov eax, 1
    jmp and_end17
and_short16:
    xor eax, eax
and_end17:
    test eax, eax
    jz while_end15
    mov eax, [ebp-24]
    push eax
    mov eax, 15
    mov ebx, eax
    pop eax
    and eax, ebx
    mov [ebp-28], eax
    mov eax, [ebp-28]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else19
    mov eax, 48
    push eax
    mov eax, [ebp-28]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    lea eax, [ebp-12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    jmp endif18
else19:
    mov eax, 87
    push eax
    mov eax, [ebp-28]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    lea eax, [ebp-12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
endif18:
    mov eax, [ebp-24]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    mov ecx, ebx
    shr eax, cl
    mov [ebp-24], eax
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-20], eax
    jmp while_start14
while_end15:
    lea eax, [ebp-12]
    push eax
    call print
    add esp, 4
print_hex_return:
    mov esp, ebp
    pop ebp
    ret
    
alloc:
    push ebp
    mov ebp, esp
    sub esp, 8
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-4]
    jmp alloc_return
alloc_return:
    mov esp, ebp
    pop ebp
    ret
    
streq:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start20:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short22
    test ebx, ebx
    jz and_short22
    mov eax, 1
    jmp and_end23
and_short22:
    xor eax, eax
and_end23:
    test eax, eax
    jz while_end21
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    movzx eax, byte [eax]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else25
    mov eax, 0
    jmp streq_return
    jmp endif24
else25:
endif24:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start20
while_end21:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    movzx eax, byte [eax]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else27
    mov eax, 0
    jmp streq_return
    jmp endif26
else27:
endif26:
    mov eax, 1
    jmp streq_return
streq_return:
    mov esp, ebp
    pop ebp
    ret
    
memcpy:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start28:
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+16]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end29
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start28
while_end29:
memcpy_return:
    mov esp, ebp
    pop ebp
    ret
    
read_u32:
    push ebp
    mov ebp, esp
    sub esp, 20
    mov eax, [ebp+8]
    push eax
    mov eax, [ebp+12]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    movzx eax, byte [eax]
    mov [ebp-8], eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    movzx eax, byte [eax]
    mov [ebp-12], eax
    mov eax, 2
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    movzx eax, byte [eax]
    mov [ebp-16], eax
    mov eax, 3
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    movzx eax, byte [eax]
    mov [ebp-20], eax
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    mov ecx, ebx
    shl eax, cl
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    mov ecx, ebx
    shl eax, cl
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 24
    mov ebx, eax
    pop eax
    mov ecx, ebx
    shl eax, cl
    mov ebx, eax
    pop eax
    add eax, ebx
    jmp read_u32_return
read_u32_return:
    mov esp, ebp
    pop ebp
    ret
    
read_u16:
    push ebp
    mov ebp, esp
    sub esp, 12
    mov eax, [ebp+8]
    push eax
    mov eax, [ebp+12]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    movzx eax, byte [eax]
    mov [ebp-8], eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    movzx eax, byte [eax]
    mov [ebp-12], eax
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    mov ecx, ebx
    shl eax, cl
    mov ebx, eax
    pop eax
    add eax, ebx
    jmp read_u16_return
read_u16_return:
    mov esp, ebp
    pop ebp
    ret
    
write_u32:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, [ebp+8]
    push eax
    mov eax, [ebp+12]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    mov eax, [ebp+16]
    push eax
    mov eax, 255
    mov ebx, eax
    pop eax
    and eax, ebx
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp+16]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    mov ecx, ebx
    shr eax, cl
    push eax
    mov eax, 255
    mov ebx, eax
    pop eax
    and eax, ebx
    push eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp+16]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    mov ecx, ebx
    shr eax, cl
    push eax
    mov eax, 255
    mov ebx, eax
    pop eax
    and eax, ebx
    push eax
    mov eax, 2
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp+16]
    push eax
    mov eax, 24
    mov ebx, eax
    pop eax
    mov ecx, ebx
    shr eax, cl
    push eax
    mov eax, 255
    mov ebx, eax
    pop eax
    and eax, ebx
    push eax
    mov eax, 3
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
write_u32_return:
    mov esp, ebp
    pop ebp
    ret
    
write_u16:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, [ebp+8]
    push eax
    mov eax, [ebp+12]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    mov eax, [ebp+16]
    push eax
    mov eax, 255
    mov ebx, eax
    pop eax
    and eax, ebx
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp+16]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    mov ecx, ebx
    shr eax, cl
    push eax
    mov eax, 255
    mov ebx, eax
    pop eax
    and eax, ebx
    push eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
write_u16_return:
    mov esp, ebp
    pop ebp
    ret
    
find_or_add_symbol:
    push ebp
    mov ebp, esp
    sub esp, 28
    mov eax, 0
    mov [ebp-4], eax
while_start30:
    mov eax, [ebp-4]
    push eax
    mov eax, [rel g_sym_count]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end31
    mov eax, [ebp-4]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [rel g_sym_offsets]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-8], eax
    mov eax, [rel g_sym_names]
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    mov eax, [ebp+8]
    push eax
    mov eax, [ebp-12]
    push eax
    call streq
    add esp, 8
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else33
    mov eax, [ebp-4]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [rel g_sym_sections]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-16], eax
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short36
    test ebx, ebx
    jz and_short36
    mov eax, 1
    jmp and_end37
and_short36:
    xor eax, eax
and_end37:
    test eax, eax
    jz else35
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [rel g_sym_values]
    push eax
    call write_u32
    add esp, 12
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [rel g_sym_sections]
    push eax
    call write_u32
    add esp, 12
    jmp endif34
else35:
endif34:
    mov eax, [ebp-4]
    jmp find_or_add_symbol_return
    jmp endif32
else33:
endif32:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start30
while_end31:
    mov eax, [rel g_sym_count]
    push eax
    mov eax, 4096
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else39
    lea eax, [rel str_1]
    push eax
    call print_err
    add esp, 4
    mov eax, 1
    mov [rel g_error], eax
    mov eax, 1
    neg eax
    jmp find_or_add_symbol_return
    jmp endif38
else39:
endif38:
    mov eax, [ebp+8]
    push eax
    call strlen
    add esp, 4
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-20], eax
    mov eax, [rel g_sym_name_len]
    mov [ebp-24], eax
    mov eax, [ebp-20]
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, [rel g_sym_names]
    push eax
    mov eax, [rel g_sym_name_len]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    call memcpy
    add esp, 12
    mov eax, [rel g_sym_name_len]
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [rel g_sym_name_len], eax
    mov eax, [rel g_sym_count]
    mov [ebp-28], eax
    mov eax, [ebp-24]
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [rel g_sym_offsets]
    push eax
    call write_u32
    add esp, 12
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [rel g_sym_values]
    push eax
    call write_u32
    add esp, 12
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [rel g_sym_sections]
    push eax
    call write_u32
    add esp, 12
    mov eax, [rel g_sym_count]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [rel g_sym_count], eax
    mov eax, [ebp-28]
    jmp find_or_add_symbol_return
find_or_add_symbol_return:
    mov esp, ebp
    pop ebp
    ret
    
parse_object_file:
    push ebp
    mov ebp, esp
    sub esp, 208
    mov eax, 0
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 1179403647
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else41
    lea eax, [rel str_2]
    push eax
    call print_err
    add esp, 4
    mov eax, [ebp+8]
    push eax
    call print_err
    add esp, 4
    lea eax, [rel str_3]
    push eax
    call print_err
    add esp, 4
    mov eax, 1
    jmp parse_object_file_return
    jmp endif40
else41:
endif40:
    mov eax, 16
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u16
    add esp, 8
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else43
    lea eax, [rel str_4]
    push eax
    call print_err
    add esp, 4
    mov eax, 1
    jmp parse_object_file_return
    jmp endif42
else43:
endif42:
    mov eax, 32
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-12], eax
    mov eax, 46
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u16
    add esp, 8
    mov [ebp-16], eax
    mov eax, 48
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u16
    add esp, 8
    mov [ebp-20], eax
    mov eax, 50
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u16
    add esp, 8
    mov [ebp-24], eax
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-28], eax
    mov eax, [ebp-28]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-32], eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp-32]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-36], eax
    mov eax, 1
    neg eax
    mov [ebp-40], eax
    mov eax, 0
    mov [ebp-44], eax
    mov eax, 0
    mov [ebp-48], eax
    mov eax, 1
    neg eax
    mov [ebp-52], eax
    mov eax, 0
    mov [ebp-56], eax
    mov eax, 0
    mov [ebp-60], eax
    mov eax, 1
    neg eax
    mov [ebp-64], eax
    mov eax, 0
    mov [ebp-68], eax
    mov eax, 0
    mov [ebp-72], eax
    mov eax, 0
    mov [ebp-76], eax
    mov eax, 0
    mov [ebp-80], eax
    mov eax, 0
    mov [ebp-84], eax
    mov eax, 0
    mov [ebp-88], eax
    mov eax, 0
    mov [ebp-92], eax
    mov eax, 0
    mov [ebp-96], eax
    mov eax, 0
    mov [ebp-100], eax
while_start44:
    mov eax, [ebp-100]
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end45
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-100]
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-104], eax
    mov eax, [ebp-104]
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-108], eax
    mov eax, [ebp-104]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-112], eax
    mov eax, [ebp-104]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-116], eax
    mov eax, [ebp-104]
    push eax
    mov eax, 20
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-120], eax
    mov eax, [ebp-104]
    push eax
    mov eax, 24
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-124], eax
    mov eax, [ebp-104]
    push eax
    mov eax, 36
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-128], eax
    mov eax, [ebp-36]
    push eax
    mov eax, [ebp-108]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-132], eax
    lea eax, [rel str_5]
    push eax
    mov eax, [ebp-132]
    push eax
    call streq
    add esp, 8
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else47
    mov eax, [ebp-100]
    mov [ebp-40], eax
    mov eax, [ebp-120]
    mov [ebp-44], eax
    mov eax, [ebp-116]
    mov [ebp-48], eax
    jmp endif46
else47:
    lea eax, [rel str_6]
    push eax
    mov eax, [ebp-132]
    push eax
    call streq
    add esp, 8
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else49
    mov eax, [ebp-100]
    mov [ebp-52], eax
    mov eax, [ebp-120]
    mov [ebp-56], eax
    mov eax, [ebp-116]
    mov [ebp-60], eax
    jmp endif48
else49:
    lea eax, [rel str_7]
    push eax
    mov eax, [ebp-132]
    push eax
    call streq
    add esp, 8
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else51
    mov eax, [ebp-100]
    mov [ebp-64], eax
    mov eax, [ebp-120]
    mov [ebp-68], eax
    jmp endif50
else51:
    mov eax, [ebp-112]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else53
    mov eax, [ebp-116]
    mov [ebp-72], eax
    mov eax, [ebp-120]
    mov [ebp-76], eax
    mov eax, [ebp-128]
    mov [ebp-80], eax
    mov eax, [ebp-124]
    mov [ebp-84], eax
    jmp endif52
else53:
    lea eax, [rel str_8]
    push eax
    mov eax, [ebp-132]
    push eax
    call streq
    add esp, 8
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else55
    mov eax, [ebp-116]
    mov [ebp-92], eax
    mov eax, [ebp-120]
    mov [ebp-96], eax
    jmp endif54
else55:
endif54:
endif52:
endif50:
endif48:
endif46:
    mov eax, [ebp-100]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-100], eax
    jmp while_start44
while_end45:
    mov eax, [ebp-84]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else57
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-84]
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-136], eax
    mov eax, [ebp-136]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-88], eax
    jmp endif56
else57:
endif56:
    mov eax, 1024
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    call alloc
    add esp, 4
    mov [ebp-140], eax
    mov eax, [ebp-76]
    push eax
    mov eax, [ebp-80]
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov [ebp-144], eax
    mov eax, [rel g_data_len]
    push eax
    mov eax, [ebp-56]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-148], eax
    mov eax, [ebp-148]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov eax, edx
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else59
    mov eax, [ebp-148]
    push eax
    mov eax, 4
    push eax
    mov eax, [ebp-148]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov eax, edx
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-148], eax
    jmp endif58
else59:
endif58:
    mov eax, 0
    mov [ebp-100], eax
while_start60:
    mov eax, [ebp-100]
    push eax
    mov eax, [ebp-144]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end61
    mov eax, [ebp-72]
    push eax
    mov eax, [ebp-100]
    push eax
    mov eax, [ebp-80]
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-152], eax
    mov eax, [ebp-152]
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-156], eax
    mov eax, [ebp-152]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-160], eax
    mov eax, [ebp-152]
    push eax
    mov eax, 12
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    movzx eax, byte [eax]
    mov [ebp-164], eax
    mov eax, [ebp-152]
    push eax
    mov eax, 14
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u16
    add esp, 8
    mov [ebp-168], eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp-88]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-156]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-172], eax
    mov eax, 0
    mov [ebp-176], eax
    mov eax, [ebp-160]
    mov [ebp-180], eax
    mov eax, [ebp-168]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else63
    mov eax, 0
    mov [ebp-176], eax
    jmp endif62
else63:
    mov eax, [ebp-168]
    push eax
    mov eax, [ebp-40]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else65
    mov eax, 1
    mov [ebp-176], eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-160]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-180], eax
    jmp endif64
else65:
    mov eax, [ebp-168]
    push eax
    mov eax, [ebp-52]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else67
    mov eax, 2
    mov [ebp-176], eax
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp-160]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-180], eax
    jmp endif66
else67:
    mov eax, [ebp-168]
    push eax
    mov eax, [ebp-64]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else69
    mov eax, 3
    mov [ebp-176], eax
    mov eax, [ebp-148]
    push eax
    mov eax, [ebp-160]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-180], eax
    jmp endif68
else69:
endif68:
endif66:
endif64:
endif62:
    mov eax, [ebp-100]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else71
    mov eax, [ebp-176]
    push eax
    mov eax, [ebp-180]
    push eax
    mov eax, [ebp-172]
    push eax
    call find_or_add_symbol
    add esp, 12
    mov [ebp-184], eax
    mov eax, [ebp-184]
    push eax
    mov eax, [ebp-100]
    mov ebx, eax
    mov eax, [ebp-140]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    lea eax, [rel str_9]
    push eax
    mov eax, [ebp-172]
    push eax
    call streq
    add esp, 8
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else73
    mov eax, [ebp-180]
    mov [rel g_entry_point], eax
    jmp endif72
else73:
endif72:
    jmp endif70
else71:
    mov eax, 1
    neg eax
    push eax
    mov eax, [ebp-100]
    mov ebx, eax
    mov eax, [ebp-140]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
endif70:
    mov eax, [ebp-100]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-100], eax
    jmp while_start60
while_end61:
    mov eax, [ebp-44]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else75
    mov eax, [ebp-44]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp-48]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [rel g_text]
    push eax
    mov eax, [ebp+20]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    call memcpy
    add esp, 12
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-44]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [rel g_text_len], eax
    jmp endif74
else75:
endif74:
    mov eax, [ebp-56]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else77
    mov eax, [ebp-56]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp-60]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [rel g_data]
    push eax
    mov eax, [ebp+24]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    call memcpy
    add esp, 12
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp-56]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [rel g_data_len], eax
    jmp endif76
else77:
endif76:
    mov eax, [rel g_bss_len]
    push eax
    mov eax, [ebp-68]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [rel g_bss_len], eax
    mov eax, [ebp-96]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else79
    mov eax, [ebp-96]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov [ebp-188], eax
    mov eax, 0
    mov [ebp-100], eax
while_start80:
    mov eax, [ebp-100]
    push eax
    mov eax, [ebp-188]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end81
    mov eax, [ebp-92]
    push eax
    mov eax, [ebp-100]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-192], eax
    mov eax, [ebp-192]
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-196], eax
    mov eax, [ebp-192]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+12]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-200], eax
    mov eax, [ebp-200]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    mov ecx, ebx
    shr eax, cl
    mov [ebp-204], eax
    mov eax, [ebp-200]
    push eax
    mov eax, 255
    mov ebx, eax
    pop eax
    and eax, ebx
    mov [ebp-208], eax
    mov eax, [rel g_reloc_count]
    push eax
    mov eax, 4096
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else83
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-196]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [rel g_reloc_count]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [rel g_reloc_offsets]
    push eax
    call write_u32
    add esp, 12
    mov eax, [ebp-208]
    push eax
    mov eax, [rel g_reloc_count]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [rel g_reloc_types]
    push eax
    call write_u32
    add esp, 12
    mov eax, [ebp-204]
    mov ebx, eax
    mov eax, [ebp-140]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    push eax
    mov eax, [rel g_reloc_count]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [rel g_reloc_syms]
    push eax
    call write_u32
    add esp, 12
    mov eax, [rel g_reloc_count]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [rel g_reloc_count], eax
    jmp endif82
else83:
endif82:
    mov eax, [ebp-100]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-100], eax
    jmp while_start80
while_end81:
    jmp endif78
else79:
endif78:
    mov eax, 0
    jmp parse_object_file_return
parse_object_file_return:
    mov esp, ebp
    pop ebp
    ret
    
apply_relocations:
    push ebp
    mov ebp, esp
    sub esp, 52
    mov eax, 0
    mov [ebp-4], eax
while_start84:
    mov eax, [ebp-4]
    push eax
    mov eax, [rel g_reloc_count]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end85
    mov eax, [ebp-4]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [rel g_reloc_offsets]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-8], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [rel g_reloc_types]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-12], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [rel g_reloc_syms]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-16], eax
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, [rel g_sym_count]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jnz or_short88
    test ebx, ebx
    jnz or_short88
    xor eax, eax
    jmp or_end89
or_short88:
    mov eax, 1
or_end89:
    test eax, eax
    jz else87
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start84
    jmp endif86
else87:
endif86:
    mov eax, [ebp-16]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [rel g_sym_values]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-20], eax
    mov eax, [ebp-16]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [rel g_sym_sections]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-24], eax
    mov eax, [ebp-24]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else91
    mov eax, [ebp-16]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [rel g_sym_offsets]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-28], eax
    mov eax, [rel g_sym_names]
    push eax
    mov eax, [ebp-28]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-32], eax
    lea eax, [rel str_10]
    push eax
    call print_err
    add esp, 4
    mov eax, [ebp-32]
    push eax
    call print_err
    add esp, 4
    lea eax, [rel str_11]
    push eax
    call print_err
    add esp, 4
    mov eax, 1
    jmp apply_relocations_return
    jmp endif90
else91:
endif90:
    mov eax, 0
    mov [ebp-36], eax
    mov eax, [ebp-24]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else93
    mov eax, 134516736
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-36], eax
    jmp endif92
else93:
    mov eax, [ebp-24]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else95
    mov eax, 134520832
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-36], eax
    jmp endif94
else95:
    mov eax, [ebp-24]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else97
    mov eax, 134520832
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-36], eax
    jmp endif96
else97:
endif96:
endif94:
endif92:
    mov eax, [ebp-8]
    push eax
    mov eax, [rel g_text]
    push eax
    call read_u32
    add esp, 8
    mov [ebp-40], eax
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else99
    mov eax, [ebp-36]
    push eax
    mov eax, [ebp-40]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-44], eax
    mov eax, [ebp-44]
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, [rel g_text]
    push eax
    call write_u32
    add esp, 12
    jmp endif98
else99:
    mov eax, [ebp-12]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else101
    mov eax, 134516736
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-48], eax
    mov eax, [ebp-36]
    push eax
    mov eax, [ebp-40]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-48]
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-52], eax
    mov eax, [ebp-52]
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, [rel g_text]
    push eax
    call write_u32
    add esp, 12
    jmp endif100
else101:
endif100:
endif98:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start84
while_end85:
    mov eax, 0
    jmp apply_relocations_return
apply_relocations_return:
    mov esp, ebp
    pop ebp
    ret
    
write_elf_header:
    push ebp
    mov ebp, esp
    sub esp, 8
    mov eax, [rel g_output]
    mov [ebp-4], eax
    mov eax, 127
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 69
    push eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 76
    push eax
    mov eax, 2
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 70
    push eax
    mov eax, 3
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 1
    push eax
    mov eax, 4
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 1
    push eax
    mov eax, 5
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 1
    push eax
    mov eax, 6
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 7
    mov [ebp-8], eax
while_start102:
    mov eax, [ebp-8]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end103
    mov eax, 0
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    jmp while_start102
while_end103:
    mov eax, 2
    push eax
    mov eax, 16
    push eax
    mov eax, [ebp-4]
    push eax
    call write_u16
    add esp, 12
    mov eax, 3
    push eax
    mov eax, 18
    push eax
    mov eax, [ebp-4]
    push eax
    call write_u16
    add esp, 12
    mov eax, 1
    push eax
    mov eax, 20
    push eax
    mov eax, [ebp-4]
    push eax
    call write_u32
    add esp, 12
    mov eax, 134516736
    push eax
    mov eax, [rel g_entry_point]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 24
    push eax
    mov eax, [ebp-4]
    push eax
    call write_u32
    add esp, 12
    mov eax, 52
    push eax
    mov eax, 28
    push eax
    mov eax, [ebp-4]
    push eax
    call write_u32
    add esp, 12
    mov eax, 0
    push eax
    mov eax, 32
    push eax
    mov eax, [ebp-4]
    push eax
    call write_u32
    add esp, 12
    mov eax, 0
    push eax
    mov eax, 36
    push eax
    mov eax, [ebp-4]
    push eax
    call write_u32
    add esp, 12
    mov eax, 52
    push eax
    mov eax, 40
    push eax
    mov eax, [ebp-4]
    push eax
    call write_u16
    add esp, 12
    mov eax, 32
    push eax
    mov eax, 42
    push eax
    mov eax, [ebp-4]
    push eax
    call write_u16
    add esp, 12
    mov eax, 3
    push eax
    mov eax, 44
    push eax
    mov eax, [ebp-4]
    push eax
    call write_u16
    add esp, 12
    mov eax, 0
    push eax
    mov eax, 46
    push eax
    mov eax, [ebp-4]
    push eax
    call write_u16
    add esp, 12
    mov eax, 0
    push eax
    mov eax, 48
    push eax
    mov eax, [ebp-4]
    push eax
    call write_u16
    add esp, 12
    mov eax, 0
    push eax
    mov eax, 50
    push eax
    mov eax, [ebp-4]
    push eax
    call write_u16
    add esp, 12
    mov eax, 52
    mov [rel g_output_len], eax
write_elf_header_return:
    mov esp, ebp
    pop ebp
    ret
    
write_program_headers:
    push ebp
    mov ebp, esp
    sub esp, 20
    mov eax, 52
    push eax
    mov eax, 96
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    mov eax, 4096
    mov [ebp-8], eax
    mov eax, 8192
    mov [ebp-12], eax
    mov eax, [rel g_output]
    push eax
    mov eax, 52
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-16], eax
    mov eax, 1
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, 0
    push eax
    mov eax, 4
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, 134512640
    push eax
    mov eax, 8
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, 134512640
    push eax
    mov eax, 12
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, [ebp-4]
    push eax
    mov eax, 16
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, [ebp-4]
    push eax
    mov eax, 20
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, 4
    push eax
    mov eax, 24
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, 4096
    push eax
    mov eax, 28
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, [rel g_output]
    push eax
    mov eax, 52
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-16], eax
    mov eax, 1
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, [ebp-8]
    push eax
    mov eax, 4
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, 134516736
    push eax
    mov eax, 8
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, 134516736
    push eax
    mov eax, 12
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, [rel g_text_len]
    push eax
    mov eax, 16
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, [rel g_text_len]
    push eax
    mov eax, 20
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, 5
    push eax
    mov eax, 24
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, 4096
    push eax
    mov eax, 28
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, [rel g_output]
    push eax
    mov eax, 52
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-16], eax
    mov eax, 1
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, [ebp-12]
    push eax
    mov eax, 4
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, 134520832
    push eax
    mov eax, 8
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, 134520832
    push eax
    mov eax, 12
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, [rel g_data_len]
    push eax
    mov eax, 16
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, [rel g_data_len]
    mov [ebp-20], eax
    mov eax, [ebp-20]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov eax, edx
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else105
    mov eax, [ebp-20]
    push eax
    mov eax, 4
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov eax, edx
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-20], eax
    jmp endif104
else105:
endif104:
    mov eax, [ebp-20]
    push eax
    mov eax, [rel g_bss_len]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 20
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, 6
    push eax
    mov eax, 24
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, 4096
    push eax
    mov eax, 28
    push eax
    mov eax, [ebp-16]
    push eax
    call write_u32
    add esp, 12
    mov eax, 52
    push eax
    mov eax, 96
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [rel g_output_len], eax
write_program_headers_return:
    mov esp, ebp
    pop ebp
    ret
    
write_output:
    push ebp
    mov ebp, esp
    sub esp, 4
    call write_elf_header
    call write_program_headers
while_start106:
    mov eax, [rel g_output_len]
    push eax
    mov eax, 4096
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end107
    mov eax, 0
    push eax
    mov eax, [rel g_output_len]
    mov ebx, eax
    mov eax, [rel g_output]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [rel g_output_len]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [rel g_output_len], eax
    jmp while_start106
while_end107:
    mov eax, [rel g_text_len]
    push eax
    mov eax, [rel g_text]
    push eax
    mov eax, [rel g_output]
    push eax
    mov eax, [rel g_output_len]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    call memcpy
    add esp, 12
    mov eax, [rel g_output_len]
    push eax
    mov eax, [rel g_text_len]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [rel g_output_len], eax
while_start108:
    mov eax, [rel g_output_len]
    push eax
    mov eax, 8192
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end109
    mov eax, 0
    push eax
    mov eax, [rel g_output_len]
    mov ebx, eax
    mov eax, [rel g_output]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [rel g_output_len]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [rel g_output_len], eax
    jmp while_start108
while_end109:
    mov eax, [rel g_data_len]
    push eax
    mov eax, [rel g_data]
    push eax
    mov eax, [rel g_output]
    push eax
    mov eax, [rel g_output_len]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    call memcpy
    add esp, 12
    mov eax, [rel g_output_len]
    push eax
    mov eax, [rel g_data_len]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [rel g_output_len], eax
    mov eax, 493
    push eax
    mov eax, 1
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 512
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 5
    push eax
    call syscall3
    add esp, 16
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else111
    lea eax, [rel str_12]
    push eax
    call print_err
    add esp, 4
    mov eax, 1
    jmp write_output_return
    jmp endif110
else111:
endif110:
    mov eax, [rel g_output_len]
    push eax
    mov eax, [rel g_output]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    mov eax, [ebp-4]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
    mov eax, 0
    jmp write_output_return
write_output_return:
    mov esp, ebp
    pop ebp
    ret
    
main:
    push ebp
    mov ebp, esp
    sub esp, 44
    lea eax, [rel str_13]
    push eax
    call println
    add esp, 4
    call get_argc
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else113
    lea eax, [rel str_14]
    push eax
    call println
    add esp, 4
    mov eax, 1
    jmp main_return
    jmp endif112
else113:
endif112:
    mov eax, 1048576
    push eax
    call alloc
    add esp, 4
    mov [rel g_output], eax
    mov eax, 1048576
    mov [rel g_output_cap], eax
    mov eax, 262144
    push eax
    call alloc
    add esp, 4
    mov [rel g_text], eax
    mov eax, 262144
    push eax
    call alloc
    add esp, 4
    mov [rel g_data], eax
    mov eax, 65536
    push eax
    call alloc
    add esp, 4
    mov [rel g_sym_names], eax
    mov eax, 4096
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    call alloc
    add esp, 4
    mov [rel g_sym_values], eax
    mov eax, 4096
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    call alloc
    add esp, 4
    mov [rel g_sym_sections], eax
    mov eax, 4096
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    call alloc
    add esp, 4
    mov [rel g_sym_offsets], eax
    mov eax, 4096
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    call alloc
    add esp, 4
    mov [rel g_reloc_offsets], eax
    mov eax, 4096
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    call alloc
    add esp, 4
    mov [rel g_reloc_types], eax
    mov eax, 4096
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    call alloc
    add esp, 4
    mov [rel g_reloc_syms], eax
    mov eax, 0
    mov [ebp-8], eax
    mov eax, 1
    mov [ebp-12], eax
while_start114:
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end115
    mov eax, [ebp-12]
    push eax
    call get_argv
    add esp, 4
    mov [ebp-16], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 45
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    push eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 111
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short118
    test ebx, ebx
    jz and_short118
    mov eax, 1
    jmp and_end119
and_short118:
    xor eax, eax
and_end119:
    test eax, eax
    jz else117
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else121
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    call get_argv
    add esp, 4
    mov [ebp-8], eax
    jmp endif120
else121:
endif120:
    mov eax, [ebp-12]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    jmp endif116
else117:
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
endif116:
    jmp while_start114
while_end115:
    mov eax, [ebp-8]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else123
    lea eax, [rel str_15]
    push eax
    call print_err
    add esp, 4
    mov eax, 1
    jmp main_return
    jmp endif122
else123:
endif122:
    lea eax, [rel str_16]
    push eax
    call print
    add esp, 4
    mov eax, [ebp-8]
    push eax
    call println
    add esp, 4
    mov eax, 0
    mov [ebp-20], eax
    mov eax, 0
    mov [ebp-24], eax
    mov eax, 1
    mov [ebp-12], eax
while_start124:
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end125
    mov eax, [ebp-12]
    push eax
    call get_argv
    add esp, 4
    mov [ebp-28], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-28]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 45
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    push eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-28]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 111
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short128
    test ebx, ebx
    jz and_short128
    mov eax, 1
    jmp and_end129
and_short128:
    xor eax, eax
and_end129:
    test eax, eax
    jz else127
    mov eax, [ebp-12]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    jmp while_start124
    jmp endif126
else127:
endif126:
    lea eax, [rel str_17]
    push eax
    call print
    add esp, 4
    mov eax, [ebp-28]
    push eax
    call println
    add esp, 4
    mov eax, 0
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 5
    push eax
    call syscall3
    add esp, 16
    mov [ebp-32], eax
    mov eax, [ebp-32]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else131
    lea eax, [rel str_18]
    push eax
    call print_err
    add esp, 4
    mov eax, [ebp-28]
    push eax
    call print_err
    add esp, 4
    lea eax, [rel str_19]
    push eax
    call print_err
    add esp, 4
    mov eax, 1
    jmp main_return
    jmp endif130
else131:
endif130:
    mov eax, 262144
    push eax
    call alloc
    add esp, 4
    mov [ebp-36], eax
    mov eax, 0
    mov [ebp-40], eax
    mov eax, 262144
    push eax
    mov eax, [ebp-36]
    push eax
    mov eax, [ebp-32]
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-44], eax
while_start132:
    mov eax, [ebp-44]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz while_end133
    mov eax, [ebp-40]
    push eax
    mov eax, [ebp-44]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-40], eax
    mov eax, 262144
    push eax
    mov eax, [ebp-40]
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp-36]
    push eax
    mov eax, [ebp-40]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-32]
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-44], eax
    jmp while_start132
while_end133:
    mov eax, [ebp-32]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-24]
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, [ebp-40]
    push eax
    mov eax, [ebp-36]
    push eax
    mov eax, [ebp-28]
    push eax
    call parse_object_file
    add esp, 20
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else135
    mov eax, 1
    jmp main_return
    jmp endif134
else135:
endif134:
    mov eax, [rel g_text_len]
    mov [ebp-20], eax
    mov eax, [rel g_data_len]
    mov [ebp-24], eax
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    jmp while_start124
while_end125:
    lea eax, [rel str_20]
    push eax
    call print
    add esp, 4
    mov eax, [rel g_sym_count]
    push eax
    call print_num
    add esp, 4
    lea eax, [rel str_21]
    push eax
    call println
    add esp, 4
    lea eax, [rel str_22]
    push eax
    call print
    add esp, 4
    mov eax, [rel g_reloc_count]
    push eax
    call print_num
    add esp, 4
    lea eax, [rel str_23]
    push eax
    call println
    add esp, 4
    call apply_relocations
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else137
    mov eax, 1
    jmp main_return
    jmp endif136
else137:
endif136:
    lea eax, [rel str_24]
    push eax
    call print
    add esp, 4
    mov eax, [rel g_text_len]
    push eax
    call print_num
    add esp, 4
    lea eax, [rel str_25]
    push eax
    call println
    add esp, 4
    lea eax, [rel str_26]
    push eax
    call print
    add esp, 4
    mov eax, [rel g_data_len]
    push eax
    call print_num
    add esp, 4
    lea eax, [rel str_27]
    push eax
    call println
    add esp, 4
    lea eax, [rel str_28]
    push eax
    call print
    add esp, 4
    mov eax, [rel g_bss_len]
    push eax
    call print_num
    add esp, 4
    lea eax, [rel str_29]
    push eax
    call println
    add esp, 4
    lea eax, [rel str_30]
    push eax
    call print
    add esp, 4
    mov eax, 134516736
    push eax
    mov eax, [rel g_entry_point]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    call print_hex
    add esp, 4
    lea eax, [rel str_31]
    push eax
    call println
    add esp, 4
    mov eax, [ebp-8]
    push eax
    call write_output
    add esp, 4
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else139
    mov eax, 1
    jmp main_return
    jmp endif138
else139:
endif138:
    lea eax, [rel str_32]
    push eax
    call println
    add esp, 4
    mov eax, 0
    jmp main_return
main_return:
    mov esp, ebp
    pop ebp
    ret
