; Generated by Brainhair Compiler
bits 32

extern syscall1
extern syscall2
extern syscall3

section .data
str_0: db "cat: ", 0
str_1: db ": No such file or directory", 10, "", 0

section .text
global _start
global get_argc
global get_argv

section .bss
_startup_esp: resd 1

section .text

_start:
    mov [_startup_esp], esp  ; Save initial stack pointer
    call main
    ; Exit with return code from main
    mov ebx, eax  ; Exit code
    mov eax, 1    ; sys_exit
    int 0x80

; get_argc() - returns argument count
get_argc:
    mov eax, [_startup_esp]
    mov eax, [eax]  ; argc is at [esp]
    ret

; get_argv(index) - returns pointer to argument string
get_argv:
    push ebp
    mov ebp, esp
    mov eax, [_startup_esp]
    mov ecx, [ebp+8]  ; index
    lea eax, [eax + 4 + ecx*4]  ; argv[index] = esp + 4 + index*4
    mov eax, [eax]
    pop ebp
    ret
    
strlen:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start0:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end1
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start0
while_end1:
    mov eax, [ebp-4]
    jmp strlen_return
strlen_return:
    mov esp, ebp
    pop ebp
    ret
    
print_err:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, [ebp+8]
    push eax
    call strlen
    add esp, 4
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 2
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
print_err_return:
    mov esp, ebp
    pop ebp
    ret
    
cat_fd:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 4096
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-4], eax
while_start2:
    mov eax, [ebp-4]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz while_end3
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    mov eax, 4096
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-4], eax
    jmp while_start2
while_end3:
cat_fd_return:
    mov esp, ebp
    pop ebp
    ret
    
main:
    push ebp
    mov ebp, esp
    sub esp, 28
    call get_argc
    mov [ebp-4], eax
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 4096
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    mov eax, [ebp-12]
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-8]
    mov [ebp-16], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else5
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    push eax
    call cat_fd
    add esp, 8
    jmp endif4
else5:
    mov eax, 1
    mov [ebp-20], eax
while_start6:
    mov eax, [ebp-20]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end7
    mov eax, [ebp-20]
    push eax
    call get_argv
    add esp, 4
    mov [ebp-24], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-24]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 45
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else9
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-24]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else11
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    push eax
    call cat_fd
    add esp, 8
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-20], eax
    mov eax, 0
    jmp endif10
else11:
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-20], eax
    mov eax, 0
endif10:
    jmp endif8
else9:
    mov eax, 0
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 5
    push eax
    call syscall2
    add esp, 12
    mov [ebp-28], eax
    mov eax, [ebp-28]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else13
    lea eax, [rel str_0]
    push eax
    call print_err
    add esp, 4
    mov eax, [ebp-24]
    push eax
    call print_err
    add esp, 4
    lea eax, [rel str_1]
    push eax
    call print_err
    add esp, 4
    jmp endif12
else13:
    mov eax, [ebp-16]
    push eax
    mov eax, [ebp-28]
    push eax
    call cat_fd
    add esp, 8
    mov eax, [ebp-28]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
endif12:
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-20], eax
endif8:
    jmp while_start6
while_end7:
endif4:
    mov eax, 0
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
main_return:
    mov esp, ebp
    pop ebp
    ret
