; Generated by Brainhair Compiler
bits 32

extern syscall1
extern syscall2
extern syscall3

section .data
str_0: db "0", 0
str_1: db "?", 10, "", 0
str_2: db "?", 10, "", 0
str_3: db "", 9, "", 0
str_4: db "?", 10, "", 0
str_5: db "", 10, "", 0
str_6: db "?", 10, "", 0
str_7: db "", 10, "", 0
str_8: db "Buffer full", 10, "", 0
str_9: db "Too many lines", 10, "", 0
str_10: db "?", 10, "", 0
str_11: db "?", 10, "", 0
str_12: db "?", 10, "", 0
str_13: db "?", 10, "", 0
str_14: db "?", 10, "", 0
str_15: db "?", 10, "", 0
str_16: db "?", 10, "", 0
str_17: db "", 10, "", 0
str_18: db "?", 10, "", 0
str_19: db "?", 10, "", 0

section .bss
current_line: resb 4
total_lines: resb 4
buffer_used: resb 4
modified: resb 4

section .text
global _start
global get_argc
global get_argv

section .bss
_startup_esp: resd 1

section .text

_start:
    mov [_startup_esp], esp  ; Save initial stack pointer
    call main
    ; Halt (infinite loop)
.halt:
    hlt
    jmp .halt

; get_argc() - returns argument count
get_argc:
    mov eax, [_startup_esp]
    mov eax, [eax]  ; argc is at [esp]
    ret

; get_argv(index) - returns pointer to argument string
get_argv:
    push ebp
    mov ebp, esp
    mov eax, [_startup_esp]
    mov ecx, [ebp+8]  ; index
    lea eax, [eax + 4 + ecx*4]  ; argv[index] = esp + 4 + index*4
    mov eax, [eax]
    pop ebp
    ret
    
strlen:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start0:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end1
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start0
while_end1:
    mov eax, [ebp-4]
    jmp strlen_return
strlen_return:
    mov esp, ebp
    pop ebp
    ret
    
print:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, [ebp+8]
    push eax
    call strlen
    add esp, 4
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
print_return:
    mov esp, ebp
    pop ebp
    ret
    
print_err:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, [ebp+8]
    push eax
    call strlen
    add esp, 4
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 2
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
print_err_return:
    mov esp, ebp
    pop ebp
    ret
    
print_int:
    push ebp
    mov ebp, esp
    sub esp, 16
    mov eax, [ebp+8]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else3
    mov eax, 1
    push eax
    lea eax, [rel str_0]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    jmp print_int_return
    jmp endif2
else3:
endif2:
    mov eax, [ebp+8]
    mov [ebp-4], eax
    mov eax, 0
    mov [ebp-8], eax
while_start4:
    mov eax, [ebp-4]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz while_end5
    mov eax, [ebp-4]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov eax, edx
    mov [ebp-12], eax
    mov eax, 48
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-4]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov [ebp-4], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    jmp while_start4
while_end5:
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-16], eax
while_start6:
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz while_end7
    mov eax, 1
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    mov eax, [ebp-16]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-16], eax
    jmp while_start6
while_end7:
print_int_return:
    mov esp, ebp
    pop ebp
    ret
    
parse_int:
    push ebp
    mov ebp, esp
    sub esp, 8
    mov eax, 0
    mov [ebp-4], eax
    mov eax, 0
    mov [ebp-8], eax
while_start8:
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 48
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz while_end9
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 57
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    test eax, eax
    jz else11
    mov eax, [ebp-4]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 48
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-4], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    jmp endif10
else11:
    jmp while_end9
endif10:
    jmp while_start8
while_end9:
    mov eax, [ebp-4]
    jmp parse_int_return
parse_int_return:
    mov esp, ebp
    pop ebp
    ret
    
get_line:
    push ebp
    mov ebp, esp
    mov eax, [ebp+16]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else13
    mov eax, 0
    jmp get_line_return
    jmp endif12
else13:
endif12:
    mov eax, [ebp+16]
    push eax
    mov eax, [rel total_lines]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else15
    mov eax, 0
    jmp get_line_return
    jmp endif14
else15:
endif14:
    mov eax, [ebp+8]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov ebx, eax
    mov eax, [ebp+12]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    mov ebx, eax
    pop eax
    add eax, ebx
    jmp get_line_return
get_line_return:
    mov esp, ebp
    pop ebp
    ret
    
print_line:
    push ebp
    mov ebp, esp
    sub esp, 8
    mov eax, [ebp+16]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else17
    lea eax, [rel str_1]
    push eax
    call print_err
    add esp, 4
    jmp print_line_return
    jmp endif16
else17:
endif16:
    mov eax, [ebp+16]
    push eax
    mov eax, [rel total_lines]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else19
    lea eax, [rel str_2]
    push eax
    call print_err
    add esp, 4
    jmp print_line_return
    jmp endif18
else19:
endif18:
    mov eax, [ebp+20]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else21
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+16]
    push eax
    call print_int
    add esp, 8
    mov eax, 1
    push eax
    lea eax, [rel str_3]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    jmp endif20
else21:
endif20:
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call get_line
    add esp, 12
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else23
    lea eax, [rel str_4]
    push eax
    call print_err
    add esp, 4
    jmp print_line_return
    jmp endif22
else23:
endif22:
    mov eax, 0
    mov [ebp-8], eax
while_start24:
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end25
    mov eax, 1
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else27
    jmp while_end25
    jmp endif26
else27:
endif26:
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    jmp while_start24
while_end25:
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else29
    mov eax, 1
    push eax
    lea eax, [rel str_5]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    jmp endif28
else29:
endif28:
print_line_return:
    mov esp, ebp
    pop ebp
    ret
    
save_file:
    push ebp
    mov ebp, esp
    sub esp, 32
    mov eax, 256
    push eax
    mov eax, 128
    mov ebx, eax
    pop eax
    or eax, ebx
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    or eax, ebx
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    or eax, ebx
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    or eax, ebx
    push eax
    mov eax, 512
    mov ebx, eax
    pop eax
    or eax, ebx
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, 5
    push eax
    call syscall3
    add esp, 16
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else31
    lea eax, [rel str_6]
    push eax
    call print_err
    add esp, 4
    mov eax, 0
    jmp save_file_return
    jmp endif30
else31:
endif30:
    mov eax, 0
    mov [ebp-12], eax
    mov eax, 1
    mov [ebp-16], eax
while_start32:
    mov eax, [ebp-16]
    push eax
    mov eax, [rel total_lines]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    test eax, eax
    jz while_end33
    mov eax, [ebp-16]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call get_line
    add esp, 12
    mov [ebp-20], eax
    mov eax, 0
    mov [ebp-24], eax
while_start34:
    mov eax, [ebp-24]
    mov ebx, eax
    mov eax, [ebp-20]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end35
    mov eax, 1
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, [ebp-24]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    mov [ebp-28], eax
    mov eax, [ebp-28]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else37
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-28]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    jmp endif36
else37:
endif36:
    mov eax, [ebp-24]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-24], eax
    mov eax, [ebp-24]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov ebx, eax
    mov eax, [ebp-20]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else39
    jmp while_end35
    jmp endif38
else39:
endif38:
    jmp while_start34
while_end35:
    mov eax, [ebp-24]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else41
    mov eax, [ebp-24]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov ebx, eax
    mov eax, [ebp-20]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else43
    mov eax, 1
    push eax
    lea eax, [rel str_7]
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    mov [ebp-32], eax
    mov eax, [ebp-32]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else45
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-32]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    jmp endif44
else45:
endif44:
    jmp endif42
else43:
endif42:
    jmp endif40
else41:
endif40:
    mov eax, [ebp-16]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-16], eax
    jmp while_start32
while_end33:
    mov eax, [ebp-8]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
    mov eax, 0
    mov [rel modified], eax
    mov eax, [ebp-12]
    jmp save_file_return
save_file_return:
    mov esp, ebp
    pop ebp
    ret
    
insert_line:
    push ebp
    mov ebp, esp
    sub esp, 12
    mov eax, [rel buffer_used]
    push eax
    mov eax, [ebp+20]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 65536
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else47
    lea eax, [rel str_8]
    push eax
    call print_err
    add esp, 4
    jmp insert_line_return
    jmp endif46
else47:
endif46:
    mov eax, [rel total_lines]
    push eax
    mov eax, 2000
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else49
    lea eax, [rel str_9]
    push eax
    call print_err
    add esp, 4
    jmp insert_line_return
    jmp endif48
else49:
endif48:
    mov eax, [rel buffer_used]
    mov [ebp-4], eax
    mov eax, 0
    mov [ebp-8], eax
while_start50:
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp+20]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end51
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    jmp while_start50
while_end51:
    mov eax, [ebp+20]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else53
    mov eax, [ebp+20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else55
    mov eax, 10
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+20]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp+20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp+20], eax
    jmp endif54
else55:
endif54:
    jmp endif52
else53:
endif52:
    mov eax, 0
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+20]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [rel total_lines]
    mov [ebp-12], eax
while_start56:
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp+24]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz while_end57
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov ebx, eax
    mov eax, [ebp+12]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    mov eax, [ebp+12]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-12], eax
    jmp while_start56
while_end57:
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+24]
    mov ebx, eax
    mov eax, [ebp+12]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [rel total_lines]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [rel total_lines], eax
    mov eax, [rel buffer_used]
    push eax
    mov eax, [ebp+20]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [rel buffer_used], eax
    mov eax, 1
    mov [rel modified], eax
insert_line_return:
    mov esp, ebp
    pop ebp
    ret
    
delete_line:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, [ebp+12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else59
    lea eax, [rel str_10]
    push eax
    call print_err
    add esp, 4
    jmp delete_line_return
    jmp endif58
else59:
endif58:
    mov eax, [ebp+12]
    push eax
    mov eax, [rel total_lines]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else61
    lea eax, [rel str_11]
    push eax
    call print_err
    add esp, 4
    jmp delete_line_return
    jmp endif60
else61:
endif60:
    mov eax, [ebp+12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-4], eax
while_start62:
    mov eax, [ebp-4]
    push eax
    mov eax, [rel total_lines]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end63
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start62
while_end63:
    mov eax, [rel total_lines]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [rel total_lines], eax
    mov eax, [rel current_line]
    push eax
    mov eax, [rel total_lines]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else65
    mov eax, [rel total_lines]
    mov [rel current_line], eax
    jmp endif64
else65:
endif64:
    mov eax, [rel current_line]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else67
    mov eax, [rel total_lines]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else69
    mov eax, 1
    mov [rel current_line], eax
    jmp endif68
else69:
endif68:
    jmp endif66
else67:
endif66:
    mov eax, 1
    mov [rel modified], eax
delete_line_return:
    mov esp, ebp
    pop ebp
    ret
    
append_mode:
    push ebp
    mov ebp, esp
    sub esp, 13
    mov eax, [ebp+20]
    mov [ebp-4], eax
while_start70:
    mov eax, 1
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end71
    mov eax, 0
    mov [ebp-8], eax
while_start72:
    mov eax, 1
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end73
    mov eax, 1
    push eax
    lea eax, [ebp-9]
    push eax
    mov eax, 0
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-13], eax
    mov eax, [ebp-13]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    test eax, eax
    jz else75
    jmp append_mode_return
    jmp endif74
else75:
endif74:
    movzx eax, byte [ebp-9]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else77
    movzx eax, byte [ebp-9]
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    jmp while_end73
    jmp endif76
else77:
endif76:
    movzx eax, byte [ebp-9]
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 4095
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else79
    jmp while_end73
    jmp endif78
else79:
endif78:
    jmp while_start72
while_end73:
    mov eax, [ebp-8]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else81
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 46
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else83
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else85
    jmp append_mode_return
    jmp endif84
else85:
endif84:
    jmp endif82
else83:
endif82:
    jmp endif80
else81:
endif80:
    mov eax, 0
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call insert_line
    add esp, 20
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    mov eax, [ebp-4]
    mov [rel current_line], eax
    jmp while_start70
while_end71:
append_mode_return:
    mov esp, ebp
    pop ebp
    ret
    
read_command:
    push ebp
    mov ebp, esp
    sub esp, 9
    mov eax, 0
    mov [ebp-4], eax
while_start86:
    mov eax, 1
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end87
    mov eax, 1
    push eax
    lea eax, [ebp-5]
    push eax
    mov eax, 0
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-9], eax
    mov eax, [ebp-9]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    test eax, eax
    jz else89
    mov eax, 1
    neg eax
    jmp read_command_return
    jmp endif88
else89:
endif88:
    movzx eax, byte [ebp-5]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else91
    mov eax, 0
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-4]
    jmp read_command_return
    jmp endif90
else91:
endif90:
    movzx eax, byte [ebp-5]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else93
    mov eax, 0
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-4]
    jmp read_command_return
    jmp endif92
else93:
endif92:
    jmp while_start86
while_end87:
    mov eax, [ebp-4]
    jmp read_command_return
read_command_return:
    mov esp, ebp
    pop ebp
    ret
    
process_command:
    push ebp
    mov ebp, esp
    sub esp, 36
    mov eax, [ebp+28]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else95
    mov eax, [rel current_line]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else97
    mov eax, [rel current_line]
    push eax
    mov eax, [rel total_lines]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    test eax, eax
    jz else99
    mov eax, [ebp+20]
    push eax
    mov eax, 0
    push eax
    mov eax, [rel current_line]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call print_line
    add esp, 20
    jmp endif98
else99:
    lea eax, [rel str_12]
    push eax
    call print_err
    add esp, 4
endif98:
    jmp endif96
else97:
    lea eax, [rel str_13]
    push eax
    call print_err
    add esp, 4
endif96:
    mov eax, 1
    jmp process_command_return
    jmp endif94
else95:
endif94:
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 48
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else101
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 57
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    test eax, eax
    jz else103
    mov eax, [ebp+16]
    push eax
    call parse_int
    add esp, 4
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else105
    mov eax, [ebp-4]
    push eax
    mov eax, [rel total_lines]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    test eax, eax
    jz else107
    mov eax, [ebp-4]
    mov [rel current_line], eax
    mov eax, 0
    mov [ebp-8], eax
while_start108:
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 48
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz while_end109
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 57
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    test eax, eax
    jz else111
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    jmp endif110
else111:
    jmp while_end109
endif110:
    jmp while_start108
while_end109:
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else113
    mov eax, [ebp+20]
    push eax
    mov eax, 0
    push eax
    mov eax, [rel current_line]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call print_line
    add esp, 20
    mov eax, 1
    jmp process_command_return
    jmp endif112
else113:
endif112:
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-12]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 112
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else115
    mov eax, [ebp+20]
    push eax
    mov eax, 0
    push eax
    mov eax, [rel current_line]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call print_line
    add esp, 20
    mov eax, 1
    jmp process_command_return
    jmp endif114
else115:
endif114:
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-12]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 110
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else117
    mov eax, [ebp+20]
    push eax
    mov eax, 1
    push eax
    mov eax, [rel current_line]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call print_line
    add esp, 20
    mov eax, 1
    jmp process_command_return
    jmp endif116
else117:
endif116:
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-12]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 100
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else119
    mov eax, [rel current_line]
    push eax
    mov eax, [ebp+12]
    push eax
    call delete_line
    add esp, 8
    mov eax, 1
    jmp process_command_return
    jmp endif118
else119:
endif118:
    jmp endif106
else107:
    lea eax, [rel str_14]
    push eax
    call print_err
    add esp, 4
    mov eax, 1
    jmp process_command_return
endif106:
    jmp endif104
else105:
endif104:
    jmp endif102
else103:
endif102:
    jmp endif100
else101:
endif100:
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 36
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else121
    mov eax, [rel total_lines]
    mov [rel current_line], eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else123
    mov eax, [ebp+20]
    push eax
    mov eax, 0
    push eax
    mov eax, [rel current_line]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call print_line
    add esp, 20
    mov eax, 1
    jmp process_command_return
    jmp endif122
else123:
endif122:
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 112
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else125
    mov eax, [ebp+20]
    push eax
    mov eax, 0
    push eax
    mov eax, [rel current_line]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call print_line
    add esp, 20
    mov eax, 1
    jmp process_command_return
    jmp endif124
else125:
endif124:
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 110
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else127
    mov eax, [ebp+20]
    push eax
    mov eax, 1
    push eax
    mov eax, [rel current_line]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call print_line
    add esp, 20
    mov eax, 1
    jmp process_command_return
    jmp endif126
else127:
endif126:
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 100
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else129
    mov eax, [rel current_line]
    push eax
    mov eax, [ebp+12]
    push eax
    call delete_line
    add esp, 8
    mov eax, 1
    jmp process_command_return
    jmp endif128
else129:
endif128:
    jmp endif120
else121:
endif120:
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 112
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else131
    mov eax, [ebp+20]
    push eax
    mov eax, 0
    push eax
    mov eax, [rel current_line]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call print_line
    add esp, 20
    mov eax, 1
    jmp process_command_return
    jmp endif130
else131:
endif130:
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 110
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else133
    mov eax, [ebp+20]
    push eax
    mov eax, 1
    push eax
    mov eax, [rel current_line]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call print_line
    add esp, 20
    mov eax, 1
    jmp process_command_return
    jmp endif132
else133:
endif132:
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 97
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else135
    mov eax, [rel current_line]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call append_mode
    add esp, 16
    mov eax, 1
    jmp process_command_return
    jmp endif134
else135:
endif134:
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 105
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else137
    mov eax, [rel current_line]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-16], eax
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else139
    mov eax, 0
    mov [ebp-16], eax
    jmp endif138
else139:
endif138:
    mov eax, [ebp-16]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call append_mode
    add esp, 16
    mov eax, 1
    jmp process_command_return
    jmp endif136
else137:
endif136:
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 100
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else141
    mov eax, [rel current_line]
    push eax
    mov eax, [ebp+12]
    push eax
    call delete_line
    add esp, 8
    mov eax, 1
    jmp process_command_return
    jmp endif140
else141:
endif140:
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 99
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else143
    mov eax, [rel current_line]
    mov [ebp-20], eax
    mov eax, [rel current_line]
    push eax
    mov eax, [ebp+12]
    push eax
    call delete_line
    add esp, 8
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-24], eax
    mov eax, [ebp-24]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else145
    mov eax, 0
    mov [ebp-24], eax
    jmp endif144
else145:
endif144:
    mov eax, [ebp-24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call append_mode
    add esp, 16
    mov eax, 1
    jmp process_command_return
    jmp endif142
else143:
endif142:
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 119
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else147
    mov eax, [ebp+24]
    mov [ebp-28], eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else149
    mov eax, [ebp+16]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-28], eax
    jmp endif148
else149:
endif148:
    mov eax, [ebp-28]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else151
    lea eax, [rel str_15]
    push eax
    call print_err
    add esp, 4
    mov eax, 1
    jmp process_command_return
    jmp endif150
else151:
endif150:
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-28]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else153
    mov eax, [ebp+24]
    mov [ebp-28], eax
    jmp endif152
else153:
endif152:
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-28]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else155
    lea eax, [rel str_16]
    push eax
    call print_err
    add esp, 4
    mov eax, 1
    jmp process_command_return
    jmp endif154
else155:
endif154:
    mov eax, [ebp-28]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call save_file
    add esp, 12
    mov [ebp-32], eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-32]
    push eax
    call print_int
    add esp, 8
    mov eax, 1
    push eax
    lea eax, [rel str_17]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    mov eax, 1
    jmp process_command_return
    jmp endif146
else147:
endif146:
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 113
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else157
    mov eax, [rel modified]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else159
    lea eax, [rel str_18]
    push eax
    call print_err
    add esp, 4
    mov eax, 0
    mov [rel modified], eax
    mov eax, 1
    jmp process_command_return
    jmp endif158
else159:
endif158:
    mov eax, 0
    jmp process_command_return
    jmp endif156
else157:
endif156:
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 44
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else161
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 112
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else163
    mov eax, 1
    mov [ebp-36], eax
while_start164:
    mov eax, [ebp-36]
    push eax
    mov eax, [rel total_lines]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    test eax, eax
    jz while_end165
    mov eax, [ebp+20]
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp-36]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call print_line
    add esp, 20
    mov eax, [ebp-36]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-36], eax
    jmp while_start164
while_end165:
    mov eax, 1
    jmp process_command_return
    jmp endif162
else163:
endif162:
    jmp endif160
else161:
endif160:
    lea eax, [rel str_19]
    push eax
    call print_err
    add esp, 4
    mov eax, 1
    jmp process_command_return
process_command_return:
    mov esp, ebp
    pop ebp
    ret
    
main:
    push ebp
    mov ebp, esp
    sub esp, 36
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 77952
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-4]
    mov [ebp-12], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 65536
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-16], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 73536
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-20], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 73792
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-24], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 77888
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-28], eax
    mov eax, 0
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-20]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 0
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-16]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 0
    mov [rel total_lines], eax
    mov eax, 0
    mov [rel current_line], eax
    mov eax, 0
    mov [rel buffer_used], eax
    mov eax, 0
    mov [rel modified], eax
    mov eax, 1
    mov [ebp-32], eax
while_start166:
    mov eax, [ebp-32]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end167
    mov eax, 1024
    push eax
    mov eax, [ebp-24]
    push eax
    call read_command
    add esp, 8
    mov [ebp-36], eax
    mov eax, [ebp-36]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else169
    jmp while_end167
    jmp endif168
else169:
endif168:
    mov eax, [ebp-36]
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, [ebp-12]
    push eax
    call process_command
    add esp, 24
    mov [ebp-32], eax
    jmp while_start166
while_end167:
    mov eax, 0
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
main_return:
    mov esp, ebp
    pop ebp
    ret
