; Generated by Brainhair Compiler
bits 32

extern syscall1
extern syscall3

section .data
str_0: db "Start", 10, "", 0
str_1: db "Allocated all", 10, "", 0
str_2: db "Set buffer", 10, "", 0
str_3: db "Set ptrs", 10, "", 0
str_4: db "Got offset", 10, "", 0
str_5: db "Got local copy", 10, "", 0
str_6: db "Got char", 10, "", 0
str_7: db "Got char from local", 10, "", 0

section .bss
text_buffer: resb 4
line_ptrs: resb 4

section .text
global _start
global get_argc
global get_argv

section .bss
_startup_esp: resd 1

section .text

_start:
    mov [_startup_esp], esp  ; Save initial stack pointer
    call main
    ; Halt (infinite loop)
.halt:
    hlt
    jmp .halt

; get_argc() - returns argument count
get_argc:
    mov eax, [_startup_esp]
    mov eax, [eax]  ; argc is at [esp]
    ret

; get_argv(index) - returns pointer to argument string
get_argv:
    push ebp
    mov ebp, esp
    mov eax, [_startup_esp]
    mov ecx, [ebp+8]  ; index
    lea eax, [eax + 4 + ecx*4]  ; argv[index] = esp + 4 + index*4
    mov eax, [eax]
    pop ebp
    ret
    
print:
    push ebp
    mov ebp, esp
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
print_return:
    mov esp, ebp
    pop ebp
    ret
    
main:
    push ebp
    mov ebp, esp
    sub esp, 18
    mov eax, 6
    push eax
    lea eax, [rel str_0]
    push eax
    call print
    add esp, 8
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 2000
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-4]
    mov [rel text_buffer], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 1000
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [rel line_ptrs], eax
    mov eax, 14
    push eax
    lea eax, [rel str_1]
    push eax
    call print
    add esp, 8
    mov eax, 72
    push eax
    mov eax, 0
    mov ebx, eax
    lea eax, [rel text_buffer]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 105
    push eax
    mov eax, 1
    mov ebx, eax
    lea eax, [rel text_buffer]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 10
    push eax
    mov eax, 2
    mov ebx, eax
    lea eax, [rel text_buffer]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 11
    push eax
    lea eax, [rel str_2]
    push eax
    call print
    add esp, 8
    mov eax, 0
    push eax
    mov eax, 0
    mov ebx, eax
    lea eax, [rel line_ptrs]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 10
    push eax
    mov eax, 1
    mov ebx, eax
    lea eax, [rel line_ptrs]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 9
    push eax
    lea eax, [rel str_3]
    push eax
    call print
    add esp, 8
    mov eax, 0
    mov ebx, eax
    lea eax, [rel line_ptrs]
    add eax, ebx
    movzx eax, byte [eax]
    mov [ebp-12], eax
    mov eax, 11
    push eax
    lea eax, [rel str_4]
    push eax
    call print
    add esp, 8
    mov eax, [rel text_buffer]
    mov [ebp-16], eax
    mov eax, 15
    push eax
    lea eax, [rel str_5]
    push eax
    call print
    add esp, 8
    mov eax, 0
    mov ebx, eax
    lea eax, [rel text_buffer]
    add eax, ebx
    movzx eax, byte [eax]
    mov byte [ebp-17], al
    mov eax, 9
    push eax
    lea eax, [rel str_6]
    push eax
    call print
    add esp, 8
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-16]
    add eax, ebx
    movzx eax, byte [eax]
    mov byte [ebp-18], al
    mov eax, 20
    push eax
    lea eax, [rel str_7]
    push eax
    call print
    add esp, 8
    mov eax, 0
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
main_return:
    mov esp, ebp
    pop ebp
    ret
