; Generated by Mini-Nim Compiler
bits 32

extern syscall1
extern syscall3

section .data
str_0: db "Error: No schema header", 10, "", 0
str_1: db "   PID   PPID S   RSS KB  Name", 10, "", 0
str_2: db "------ ------ - -------- --------------------------------", 10, "", 0

section .text
global _start
global get_argc
global get_argv

section .bss
_startup_esp: resd 1

section .text

_start:
    mov [_startup_esp], esp  ; Save initial stack pointer
    call main
    ; Halt (infinite loop)
.halt:
    hlt
    jmp .halt

; get_argc() - returns argument count
get_argc:
    mov eax, [_startup_esp]
    mov eax, [eax]  ; argc is at [esp]
    ret

; get_argv(index) - returns pointer to argument string
get_argv:
    push ebp
    mov ebp, esp
    mov eax, [_startup_esp]
    mov ecx, [ebp+8]  ; index
    lea eax, [eax + 4 + ecx*4]  ; argv[index] = esp + 4 + index*4
    mov eax, [eax]
    pop ebp
    ret
    
print:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start0:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end1
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start0
while_end1:
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
print_return:
    mov esp, ebp
    pop ebp
    ret
    
print_char:
    push ebp
    mov ebp, esp
    mov eax, 1
    push eax
    lea eax, [ebp+8]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
print_char_return:
    mov esp, ebp
    pop ebp
    ret
    
print_int:
    push ebp
    mov ebp, esp
    sub esp, 12
    mov eax, [ebp+8]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else3
    mov eax, 48
    push eax
    call print_char
    add esp, 4
    jmp print_int_return
    jmp endif2
else3:
endif2:
    mov eax, [ebp+8]
    mov [ebp-4], eax
    mov eax, 1
    mov [ebp-8], eax
while_start4:
    mov eax, [ebp-4]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz while_end5
    mov eax, [ebp-8]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov [ebp-8], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov [ebp-4], eax
    jmp while_start4
while_end5:
    mov eax, [ebp+8]
    mov [ebp-4], eax
while_start6:
    mov eax, [ebp-8]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz while_end7
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov [ebp-12], eax
    mov eax, 48
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    call print_char
    add esp, 4
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov eax, edx
    mov [ebp-4], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov [ebp-8], eax
    jmp while_start6
while_end7:
print_int_return:
    mov esp, ebp
    pop ebp
    ret
    
print_int_padded:
    push ebp
    mov ebp, esp
    sub esp, 12
    mov eax, [ebp+8]
    mov [ebp-4], eax
    mov eax, 0
    mov [ebp-8], eax
    mov eax, [ebp+8]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else9
    mov eax, 1
    mov [ebp-8], eax
    jmp endif8
else9:
while_start10:
    mov eax, [ebp-4]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz while_end11
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov [ebp-4], eax
    jmp while_start10
while_end11:
endif8:
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-12], eax
while_start12:
    mov eax, [ebp-12]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz while_end13
    mov eax, 32
    push eax
    call print_char
    add esp, 4
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-12], eax
    jmp while_start12
while_end13:
    mov eax, [ebp+8]
    push eax
    call print_int
    add esp, 4
print_int_padded_return:
    mov esp, ebp
    pop ebp
    ret
    
print_str_padded:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start14:
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+12]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end15
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else17
    jmp while_end15
    jmp endif16
else17:
endif16:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    call print_char
    add esp, 4
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start14
while_end15:
while_start18:
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+12]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end19
    mov eax, 32
    push eax
    call print_char
    add esp, 4
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start18
while_end19:
print_str_padded_return:
    mov esp, ebp
    pop ebp
    ret
    
main:
    push ebp
    mov ebp, esp
    sub esp, 78
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 65536
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-4]
    mov [ebp-12], eax
    mov eax, 8
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 0
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-16], eax
    mov eax, [ebp-16]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else21
    lea eax, [rel str_0]
    push eax
    call print
    add esp, 4
    mov eax, 1
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
    jmp endif20
else21:
endif20:
    mov eax, 5
    mov ebx, eax
    mov eax, [ebp-12]
    add eax, ebx
    movzx eax, byte [eax]
    mov [ebp-20], eax
    mov eax, [ebp-12]
    push eax
    mov eax, 6
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-24], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-24]
    shl ebx, 1
    add eax, ebx
    movzx eax, word [eax]
    mov [ebp-28], eax
    mov eax, 4
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 0
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-16], eax
    mov eax, [ebp-12]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-32], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-32]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    mov [ebp-36], eax
    mov eax, [ebp-20]
    push eax
    mov eax, 5
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else23
    lea eax, [rel str_1]
    push eax
    call print
    add esp, 4
    lea eax, [rel str_2]
    push eax
    call print
    add esp, 4
    jmp endif22
else23:
endif22:
    mov eax, 0
    mov [ebp-40], eax
while_start24:
    mov eax, [ebp-40]
    push eax
    mov eax, [ebp-36]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end25
    mov eax, [ebp-28]
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 12
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 0
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-16], eax
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    test eax, eax
    jz else27
    jmp while_end25
    jmp endif26
else27:
endif26:
    mov eax, [ebp-20]
    push eax
    mov eax, 5
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else29
    mov eax, [ebp-12]
    push eax
    mov eax, 12
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-44], eax
    mov eax, [ebp-44]
    mov [ebp-48], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-48]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    mov [ebp-52], eax
    mov eax, 6
    push eax
    mov eax, [ebp-52]
    push eax
    call print_int_padded
    add esp, 8
    mov eax, 32
    push eax
    call print_char
    add esp, 4
    mov eax, [ebp-44]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-56], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-56]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    mov [ebp-60], eax
    mov eax, 6
    push eax
    mov eax, [ebp-60]
    push eax
    call print_int_padded
    add esp, 8
    mov eax, 32
    push eax
    call print_char
    add esp, 4
    mov eax, 8
    mov ebx, eax
    mov eax, [ebp-44]
    add eax, ebx
    movzx eax, byte [eax]
    mov byte [ebp-61], al
    movzx eax, byte [ebp-61]
    push eax
    call print_char
    add esp, 4
    mov eax, 32
    push eax
    call print_char
    add esp, 4
    mov eax, [ebp-44]
    push eax
    mov eax, 12
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-65], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-65]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    mov [ebp-69], eax
    mov eax, 8
    push eax
    mov eax, [ebp-69]
    push eax
    call print_int_padded
    add esp, 8
    mov eax, 32
    push eax
    call print_char
    add esp, 4
    mov eax, 32
    push eax
    call print_char
    add esp, 4
    mov eax, [ebp-44]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-73], eax
    mov eax, 32
    push eax
    mov eax, [ebp-73]
    push eax
    call print_str_padded
    add esp, 8
    mov eax, 10
    push eax
    call print_char
    add esp, 4
    jmp endif28
else29:
    mov eax, 0
    mov [ebp-77], eax
while_start30:
    mov eax, [ebp-77]
    push eax
    mov eax, [ebp-28]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end31
    mov eax, 12
    push eax
    mov eax, [ebp-77]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-12]
    add eax, ebx
    movzx eax, byte [eax]
    mov byte [ebp-78], al
    movzx eax, byte [ebp-78]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else33
    movzx eax, byte [ebp-78]
    push eax
    mov eax, 127
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else35
    movzx eax, byte [ebp-78]
    push eax
    call print_char
    add esp, 4
    jmp endif34
else35:
endif34:
    jmp endif32
else33:
endif32:
    mov eax, [ebp-77]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-77], eax
    jmp while_start30
while_end31:
    mov eax, 10
    push eax
    call print_char
    add esp, 4
endif28:
    mov eax, [ebp-40]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-40], eax
    jmp while_start24
while_end25:
    mov eax, 0
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
main_return:
    mov esp, ebp
    pop ebp
    ret
