; Generated by Brainhair Compiler
bits 32

extern syscall1
extern syscall2
extern syscall3

section .data
str_0: db "0", 0
str_1: db ":", 0
str_2: db ":", 0
str_3: db "", 10, "", 0
str_4: db ":", 0
str_5: db ":", 0
str_6: db "", 10, "", 0
str_7: db ":", 0
str_8: db "", 10, "", 0
str_9: db "", 10, "", 0
str_10: db "Usage: grep [OPTIONS] PATTERN [FILE...]", 10, "", 0
str_11: db "Options:", 10, "", 0
str_12: db "  -i    Case insensitive", 10, "", 0
str_13: db "  -v    Invert match", 10, "", 0
str_14: db "  -n    Show line numbers", 10, "", 0
str_15: db "  -c    Count matches", 10, "", 0
str_16: db "  -l    List files with matches", 10, "", 0
str_17: db "  -h    Hide filename", 10, "", 0
str_18: db "grep: no pattern specified", 10, "", 0
str_19: db "(standard input)", 0
str_20: db "grep: ", 0
str_21: db ": cannot open file", 10, "", 0

section .text
global _start
global get_argc
global get_argv

section .bss
_startup_esp: resd 1

section .text

_start:
    mov [_startup_esp], esp  ; Save initial stack pointer
    call main
    ; Exit with return code from main
    mov ebx, eax  ; Exit code
    mov eax, 1    ; sys_exit
    int 0x80

; get_argc() - returns argument count
get_argc:
    mov eax, [_startup_esp]
    mov eax, [eax]  ; argc is at [esp]
    ret

; get_argv(index) - returns pointer to argument string
get_argv:
    push ebp
    mov ebp, esp
    mov eax, [_startup_esp]
    mov ecx, [ebp+8]  ; index
    lea eax, [eax + 4 + ecx*4]  ; argv[index] = esp + 4 + index*4
    mov eax, [eax]
    pop ebp
    ret
    
strlen:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start0:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end1
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start0
while_end1:
    mov eax, [ebp-4]
    jmp strlen_return
strlen_return:
    mov esp, ebp
    pop ebp
    ret
    
print:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, [ebp+8]
    push eax
    call strlen
    add esp, 4
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
print_return:
    mov esp, ebp
    pop ebp
    ret
    
print_err:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, [ebp+8]
    push eax
    call strlen
    add esp, 4
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 2
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
print_err_return:
    mov esp, ebp
    pop ebp
    ret
    
strcmp:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start2:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end3
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else5
    mov eax, 1
    jmp strcmp_return
    jmp endif4
else5:
endif4:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    movzx eax, byte [eax]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else7
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    movzx eax, byte [eax]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else9
    mov eax, 1
    neg eax
    jmp strcmp_return
    jmp endif8
else9:
endif8:
    mov eax, 1
    jmp strcmp_return
    jmp endif6
else7:
endif6:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start2
while_end3:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else11
    mov eax, 0
    jmp strcmp_return
    jmp endif10
else11:
endif10:
    mov eax, 1
    neg eax
    jmp strcmp_return
strcmp_return:
    mov esp, ebp
    pop ebp
    ret
    
to_lower:
    push ebp
    mov ebp, esp
    movzx eax, byte [ebp+8]
    push eax
    mov eax, 65
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else13
    movzx eax, byte [ebp+8]
    push eax
    mov eax, 90
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    test eax, eax
    jz else15
    movzx eax, byte [ebp+8]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    add eax, ebx
    jmp to_lower_return
    jmp endif14
else15:
endif14:
    jmp endif12
else13:
endif12:
    movzx eax, byte [ebp+8]
    jmp to_lower_return
to_lower_return:
    mov esp, ebp
    pop ebp
    ret
    
print_int:
    push ebp
    mov ebp, esp
    sub esp, 28
    mov eax, [ebp+8]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else17
    mov eax, 1
    push eax
    lea eax, [rel str_0]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    jmp print_int_return
    jmp endif16
else17:
endif16:
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-4]
    mov [ebp-12], eax
    mov eax, [ebp+8]
    mov [ebp-16], eax
    mov eax, 0
    mov [ebp-20], eax
while_start18:
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz while_end19
    mov eax, [ebp-16]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov eax, edx
    mov [ebp-24], eax
    mov eax, 48
    push eax
    mov eax, [ebp-24]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    mov eax, [ebp-12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-16]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov [ebp-16], eax
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-20], eax
    jmp while_start18
while_end19:
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-28], eax
while_start20:
    mov eax, [ebp-28]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz while_end21
    mov eax, 1
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-28]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    mov eax, [ebp-28]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-28], eax
    jmp while_start20
while_end21:
print_int_return:
    mov esp, ebp
    pop ebp
    ret
    
match_pattern:
    push ebp
    mov ebp, esp
    sub esp, 57
    mov eax, [ebp+20]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else23
    mov eax, 1
    jmp match_pattern_return
    jmp endif22
else23:
endif22:
    mov eax, 0
    mov [ebp-4], eax
    mov eax, 0
    mov [ebp-8], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 94
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else25
    mov eax, 1
    mov [ebp-4], eax
    mov eax, 1
    mov [ebp-8], eax
    jmp endif24
else25:
endif24:
    mov eax, 0
    mov [ebp-12], eax
    mov eax, [ebp+20]
    mov [ebp-16], eax
    mov eax, [ebp+20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 36
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else27
    mov eax, 1
    mov [ebp-12], eax
    mov eax, [ebp+20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-16], eax
    jmp endif26
else27:
endif26:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else29
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else31
    mov eax, [ebp-16]
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-20], eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else33
    mov eax, 0
    jmp match_pattern_return
    jmp endif32
else33:
endif32:
    mov eax, 0
    mov [ebp-24], eax
while_start34:
    mov eax, [ebp-24]
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end35
    mov eax, [ebp-24]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    mov byte [ebp-25], al
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp-24]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    mov byte [ebp-26], al
    mov eax, [ebp+24]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else37
    movzx eax, byte [ebp-25]
    push eax
    call to_lower
    add esp, 4
    mov byte [ebp-25], al
    movzx eax, byte [ebp-26]
    push eax
    call to_lower
    add esp, 4
    mov byte [ebp-26], al
    jmp endif36
else37:
endif36:
    movzx eax, byte [ebp-26]
    push eax
    mov eax, 46
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else39
    mov eax, [ebp-24]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-24], eax
    jmp endif38
else39:
    movzx eax, byte [ebp-25]
    push eax
    movzx eax, byte [ebp-26]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else41
    mov eax, 0
    jmp match_pattern_return
    jmp endif40
else41:
endif40:
    mov eax, [ebp-24]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-24], eax
endif38:
    jmp while_start34
while_end35:
    mov eax, 1
    jmp match_pattern_return
    jmp endif30
else31:
endif30:
    jmp endif28
else29:
endif28:
    mov eax, 0
    mov [ebp-30], eax
    mov eax, [ebp+12]
    mov [ebp-34], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else43
    mov eax, 1
    mov [ebp-34], eax
    jmp endif42
else43:
endif42:
while_start44:
    mov eax, [ebp-30]
    push eax
    mov eax, [ebp-34]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end45
    mov eax, 1
    mov [ebp-38], eax
    mov eax, [ebp-30]
    mov [ebp-42], eax
    mov eax, [ebp-8]
    mov [ebp-46], eax
while_start46:
    mov eax, [ebp-46]
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end47
    mov eax, [ebp-46]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else49
    mov eax, [ebp-46]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 42
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else51
    mov eax, [ebp-46]
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    mov byte [ebp-47], al
    mov eax, [ebp-46]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-46], eax
    mov eax, [ebp-42]
    mov [ebp-51], eax
while_start52:
    mov eax, [ebp-42]
    push eax
    mov eax, [ebp+12]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end53
    mov eax, [ebp-42]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    mov byte [ebp-52], al
    movzx eax, byte [ebp-47]
    mov byte [ebp-53], al
    mov eax, [ebp+24]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else55
    movzx eax, byte [ebp-52]
    push eax
    call to_lower
    add esp, 4
    mov byte [ebp-52], al
    movzx eax, byte [ebp-53]
    push eax
    call to_lower
    add esp, 4
    mov byte [ebp-53], al
    jmp endif54
else55:
endif54:
    movzx eax, byte [ebp-53]
    push eax
    mov eax, 46
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else57
    mov eax, [ebp-42]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-42], eax
    jmp endif56
else57:
    movzx eax, byte [ebp-52]
    push eax
    movzx eax, byte [ebp-53]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else59
    jmp while_end53
    jmp endif58
else59:
endif58:
    mov eax, [ebp-42]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-42], eax
endif56:
    jmp while_start52
while_end53:
    jmp endif50
else51:
    mov eax, [ebp-42]
    push eax
    mov eax, [ebp+12]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else61
    mov eax, 0
    mov [ebp-38], eax
    jmp while_end47
    jmp endif60
else61:
endif60:
    mov eax, [ebp-42]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    mov byte [ebp-54], al
    mov eax, [ebp-46]
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    mov byte [ebp-55], al
    mov eax, [ebp+24]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else63
    movzx eax, byte [ebp-54]
    push eax
    call to_lower
    add esp, 4
    mov byte [ebp-54], al
    movzx eax, byte [ebp-55]
    push eax
    call to_lower
    add esp, 4
    mov byte [ebp-55], al
    jmp endif62
else63:
endif62:
    movzx eax, byte [ebp-55]
    push eax
    mov eax, 46
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else65
    mov eax, [ebp-42]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-42], eax
    mov eax, [ebp-46]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-46], eax
    jmp endif64
else65:
    movzx eax, byte [ebp-54]
    push eax
    movzx eax, byte [ebp-55]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else67
    mov eax, 0
    mov [ebp-38], eax
    jmp while_end47
    jmp endif66
else67:
endif66:
    mov eax, [ebp-42]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-42], eax
    mov eax, [ebp-46]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-46], eax
endif64:
endif50:
    jmp endif48
else49:
    mov eax, [ebp-42]
    push eax
    mov eax, [ebp+12]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else69
    mov eax, 0
    mov [ebp-38], eax
    jmp while_end47
    jmp endif68
else69:
endif68:
    mov eax, [ebp-42]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    mov byte [ebp-56], al
    mov eax, [ebp-46]
    mov ebx, eax
    mov eax, [ebp+16]
    add eax, ebx
    movzx eax, byte [eax]
    mov byte [ebp-57], al
    mov eax, [ebp+24]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else71
    movzx eax, byte [ebp-56]
    push eax
    call to_lower
    add esp, 4
    mov byte [ebp-56], al
    movzx eax, byte [ebp-57]
    push eax
    call to_lower
    add esp, 4
    mov byte [ebp-57], al
    jmp endif70
else71:
endif70:
    movzx eax, byte [ebp-57]
    push eax
    mov eax, 46
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else73
    mov eax, [ebp-42]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-42], eax
    mov eax, [ebp-46]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-46], eax
    jmp endif72
else73:
    movzx eax, byte [ebp-56]
    push eax
    movzx eax, byte [ebp-57]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else75
    mov eax, 0
    mov [ebp-38], eax
    jmp while_end47
    jmp endif74
else75:
endif74:
    mov eax, [ebp-42]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-42], eax
    mov eax, [ebp-46]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-46], eax
endif72:
endif48:
    jmp while_start46
while_end47:
    mov eax, [ebp-38]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else77
    mov eax, [ebp-46]
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else79
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else81
    mov eax, [ebp-42]
    push eax
    mov eax, [ebp+12]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else83
    mov eax, 1
    jmp match_pattern_return
    jmp endif82
else83:
endif82:
    jmp endif80
else81:
    mov eax, 1
    jmp match_pattern_return
endif80:
    jmp endif78
else79:
endif78:
    jmp endif76
else77:
endif76:
    mov eax, [ebp-30]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-30], eax
    jmp while_start44
while_end45:
    mov eax, 0
    jmp match_pattern_return
match_pattern_return:
    mov esp, ebp
    pop ebp
    ret
    
grep_file:
    push ebp
    mov ebp, esp
    sub esp, 37
    mov eax, 0
    mov [ebp-4], eax
    mov eax, 0
    mov [ebp-8], eax
    mov eax, 0
    mov [ebp-12], eax
    mov eax, 0
    mov [ebp-16], eax
    mov eax, 0
    mov [ebp-20], eax
    mov eax, 0
    mov [ebp-24], eax
    mov eax, 1
    mov [ebp-28], eax
while_start84:
    mov eax, [ebp-28]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz while_end85
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else87
    mov eax, 4096
    push eax
    mov eax, [ebp+48]
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-16], eax
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    test eax, eax
    jz else89
    mov eax, 0
    mov [ebp-28], eax
    mov eax, [ebp-20]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else91
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, [ebp+52]
    push eax
    call match_pattern
    add esp, 20
    mov [ebp-32], eax
    mov eax, [ebp+28]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else93
    mov eax, [ebp-32]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else95
    mov eax, 1
    mov [ebp-32], eax
    jmp endif94
else95:
    mov eax, 0
    mov [ebp-32], eax
endif94:
    jmp endif92
else93:
endif92:
    mov eax, [ebp-32]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else97
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    mov eax, 1
    mov [ebp-24], eax
    mov eax, [ebp+36]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else99
    mov eax, [ebp+40]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else101
    mov eax, [ebp+44]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else103
    mov eax, [ebp+12]
    push eax
    call print
    add esp, 4
    mov eax, 1
    push eax
    lea eax, [rel str_1]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    jmp endif102
else103:
endif102:
    mov eax, [ebp+32]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else105
    mov eax, [ebp-4]
    push eax
    call print_int
    add esp, 4
    mov eax, 1
    push eax
    lea eax, [rel str_2]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    jmp endif104
else105:
endif104:
    mov eax, [ebp-20]
    push eax
    mov eax, [ebp+52]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    mov eax, 1
    push eax
    lea eax, [rel str_3]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    jmp endif100
else101:
endif100:
    jmp endif98
else99:
endif98:
    jmp endif96
else97:
endif96:
    jmp endif90
else91:
endif90:
    jmp while_end85
    jmp endif88
else89:
endif88:
    mov eax, 0
    mov [ebp-12], eax
    jmp endif86
else87:
endif86:
    mov eax, [ebp-12]
    mov ebx, eax
    mov eax, [ebp+48]
    add eax, ebx
    movzx eax, byte [eax]
    mov byte [ebp-33], al
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    movzx eax, byte [ebp-33]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else107
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, [ebp+52]
    push eax
    call match_pattern
    add esp, 20
    mov [ebp-37], eax
    mov eax, [ebp+28]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else109
    mov eax, [ebp-37]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else111
    mov eax, 1
    mov [ebp-37], eax
    jmp endif110
else111:
    mov eax, 0
    mov [ebp-37], eax
endif110:
    jmp endif108
else109:
endif108:
    mov eax, [ebp-37]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else113
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    mov eax, 1
    mov [ebp-24], eax
    mov eax, [ebp+36]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else115
    mov eax, [ebp+40]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else117
    mov eax, [ebp+44]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else119
    mov eax, [ebp+12]
    push eax
    call print
    add esp, 4
    mov eax, 1
    push eax
    lea eax, [rel str_4]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    jmp endif118
else119:
endif118:
    mov eax, [ebp+32]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else121
    mov eax, [ebp-4]
    push eax
    call print_int
    add esp, 4
    mov eax, 1
    push eax
    lea eax, [rel str_5]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    jmp endif120
else121:
endif120:
    mov eax, [ebp-20]
    push eax
    mov eax, [ebp+52]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    mov eax, 1
    push eax
    lea eax, [rel str_6]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    jmp endif116
else117:
endif116:
    jmp endif114
else115:
endif114:
    jmp endif112
else113:
endif112:
    mov eax, 0
    mov [ebp-20], eax
    jmp endif106
else107:
    mov eax, [ebp-20]
    push eax
    mov eax, 4096
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else123
    movzx eax, byte [ebp-33]
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    mov eax, [ebp+52]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-20], eax
    jmp endif122
else123:
endif122:
endif106:
    jmp while_start84
while_end85:
    mov eax, [ebp+36]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else125
    mov eax, [ebp+44]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else127
    mov eax, [ebp+12]
    push eax
    call print
    add esp, 4
    mov eax, 1
    push eax
    lea eax, [rel str_7]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    jmp endif126
else127:
endif126:
    mov eax, [ebp-8]
    push eax
    call print_int
    add esp, 4
    mov eax, 1
    push eax
    lea eax, [rel str_8]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    jmp endif124
else125:
    mov eax, [ebp+40]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else129
    mov eax, [ebp-24]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else131
    mov eax, [ebp+12]
    push eax
    call print
    add esp, 4
    mov eax, 1
    push eax
    lea eax, [rel str_9]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    jmp endif130
else131:
endif130:
    jmp endif128
else129:
endif128:
endif124:
    mov eax, [ebp-8]
    jmp grep_file_return
grep_file_return:
    mov esp, ebp
    pop ebp
    ret
    
main:
    push ebp
    mov ebp, esp
    sub esp, 108
    call get_argc
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else133
    lea eax, [rel str_10]
    push eax
    call print_err
    add esp, 4
    lea eax, [rel str_11]
    push eax
    call print_err
    add esp, 4
    lea eax, [rel str_12]
    push eax
    call print_err
    add esp, 4
    lea eax, [rel str_13]
    push eax
    call print_err
    add esp, 4
    lea eax, [rel str_14]
    push eax
    call print_err
    add esp, 4
    lea eax, [rel str_15]
    push eax
    call print_err
    add esp, 4
    lea eax, [rel str_16]
    push eax
    call print_err
    add esp, 4
    lea eax, [rel str_17]
    push eax
    call print_err
    add esp, 4
    mov eax, 1
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
    jmp endif132
else133:
endif132:
    mov eax, 0
    mov [ebp-8], eax
    mov eax, 0
    mov [ebp-12], eax
    mov eax, 0
    mov [ebp-16], eax
    mov eax, 0
    mov [ebp-20], eax
    mov eax, 0
    mov [ebp-24], eax
    mov eax, 0
    mov [ebp-28], eax
    mov eax, 0
    mov [ebp-32], eax
    mov eax, 0
    mov [ebp-36], eax
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-40], eax
    mov eax, [ebp-40]
    push eax
    mov eax, 16384
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-44], eax
    mov eax, [ebp-44]
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-40]
    mov [ebp-48], eax
    mov eax, [ebp-40]
    push eax
    mov eax, 4096
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-52], eax
    mov eax, [ebp-40]
    push eax
    mov eax, 8192
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-56], eax
    mov eax, 0
    mov [ebp-60], eax
    mov eax, 1
    mov [ebp-64], eax
while_start134:
    mov eax, [ebp-64]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end135
    mov eax, [ebp-64]
    push eax
    call get_argv
    add esp, 4
    mov [ebp-68], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-68]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 45
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else137
    mov eax, 1
    mov [ebp-72], eax
while_start138:
    mov eax, [ebp-72]
    mov ebx, eax
    mov eax, [ebp-68]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end139
    mov eax, [ebp-72]
    mov ebx, eax
    mov eax, [ebp-68]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 105
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else141
    mov eax, 1
    mov [ebp-8], eax
    jmp endif140
else141:
endif140:
    mov eax, [ebp-72]
    mov ebx, eax
    mov eax, [ebp-68]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 118
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else143
    mov eax, 1
    mov [ebp-12], eax
    jmp endif142
else143:
endif142:
    mov eax, [ebp-72]
    mov ebx, eax
    mov eax, [ebp-68]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 110
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else145
    mov eax, 1
    mov [ebp-16], eax
    jmp endif144
else145:
endif144:
    mov eax, [ebp-72]
    mov ebx, eax
    mov eax, [ebp-68]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 99
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else147
    mov eax, 1
    mov [ebp-20], eax
    jmp endif146
else147:
endif146:
    mov eax, [ebp-72]
    mov ebx, eax
    mov eax, [ebp-68]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 108
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else149
    mov eax, 1
    mov [ebp-24], eax
    jmp endif148
else149:
endif148:
    mov eax, [ebp-72]
    mov ebx, eax
    mov eax, [ebp-68]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 104
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else151
    mov eax, 1
    mov [ebp-28], eax
    jmp endif150
else151:
endif150:
    mov eax, [ebp-72]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-72], eax
    jmp while_start138
while_end139:
    jmp endif136
else137:
    mov eax, [ebp-32]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else153
    mov eax, [ebp-68]
    mov [ebp-32], eax
    mov eax, [ebp-64]
    mov [ebp-36], eax
    jmp endif152
else153:
    mov eax, [ebp-64]
    push eax
    mov eax, [ebp-60]
    mov ebx, eax
    mov eax, [ebp-56]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp-60]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-60], eax
endif152:
endif136:
    mov eax, [ebp-64]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-64], eax
    jmp while_start134
while_end135:
    mov eax, [ebp-32]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else155
    lea eax, [rel str_18]
    push eax
    call print_err
    add esp, 4
    mov eax, 1
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
    jmp endif154
else155:
endif154:
    mov eax, [ebp-32]
    push eax
    call strlen
    add esp, 4
    mov [ebp-76], eax
    mov eax, 0
    mov [ebp-80], eax
    mov eax, [ebp-60]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else157
    mov eax, 1
    mov [ebp-80], eax
    jmp endif156
else157:
endif156:
    mov eax, [ebp-28]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else159
    mov eax, 0
    mov [ebp-80], eax
    jmp endif158
else159:
endif158:
    mov eax, [ebp-60]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else161
    mov eax, [ebp-52]
    push eax
    mov eax, [ebp-48]
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp-76]
    push eax
    mov eax, [ebp-32]
    push eax
    lea eax, [rel str_19]
    push eax
    mov eax, 0
    push eax
    call grep_file
    add esp, 48
    jmp endif160
else161:
    mov eax, 0
    mov [ebp-84], eax
    mov eax, 0
    mov [ebp-88], eax
    mov eax, 0
    mov [ebp-92], eax
while_start162:
    mov eax, [ebp-92]
    push eax
    mov eax, [ebp-60]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end163
    mov eax, [ebp-92]
    mov ebx, eax
    mov eax, [ebp-56]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    mov [ebp-96], eax
    mov eax, [ebp-96]
    push eax
    call get_argv
    add esp, 4
    mov [ebp-100], eax
    mov eax, 0
    push eax
    mov eax, [ebp-100]
    push eax
    mov eax, 5
    push eax
    call syscall2
    add esp, 12
    mov [ebp-104], eax
    mov eax, [ebp-104]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else165
    lea eax, [rel str_20]
    push eax
    call print_err
    add esp, 4
    mov eax, [ebp-100]
    push eax
    call print_err
    add esp, 4
    lea eax, [rel str_21]
    push eax
    call print_err
    add esp, 4
    mov eax, 2
    mov [ebp-84], eax
    jmp endif164
else165:
    mov eax, [ebp-52]
    push eax
    mov eax, [ebp-48]
    push eax
    mov eax, [ebp-80]
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp-76]
    push eax
    mov eax, [ebp-32]
    push eax
    mov eax, [ebp-100]
    push eax
    mov eax, [ebp-104]
    push eax
    call grep_file
    add esp, 48
    mov [ebp-108], eax
    mov eax, [ebp-88]
    push eax
    mov eax, [ebp-108]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-88], eax
    mov eax, [ebp-104]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
endif164:
    mov eax, [ebp-92]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-92], eax
    jmp while_start162
while_end163:
    mov eax, [ebp-84]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else167
    mov eax, [ebp-88]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else169
    mov eax, 1
    mov [ebp-84], eax
    jmp endif168
else169:
endif168:
    jmp endif166
else167:
endif166:
    mov eax, [ebp-84]
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
endif160:
    mov eax, 0
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
main_return:
    mov esp, ebp
    pop ebp
    ret
