; Generated by Mini-Nim Compiler
bits 32

extern syscall1
extern syscall2
extern syscall3

section .data
str_0: db "", 10, "", 0
str_1: db "0", 0
str_2: db "", 10, "┌─── Schema ───────────────────────┐", 10, "", 0
str_3: db "│ Magic:   ", 0
str_4: db "                     │", 10, "│ Version: ", 0
str_5: db "                        │", 10, "│ Fields:  ", 0
str_6: db "                        │", 10, "│ RecSize: ", 0
str_7: db " bytes                 │", 10, "└──────────────────────────────────┘", 10, "", 0
str_8: db "", 10, "┌─── Data (", 0
str_9: db " records) ───────────────┐", 10, "", 0
str_10: db "│ [", 0
str_11: db "] ", 0
str_12: db " ", 0
str_13: db "...", 0
str_14: db " │", 10, "", 0
str_15: db "└──────────────────────────────────┘", 10, "", 0
str_16: db "Error: pipe() failed", 10, "", 0
str_17: db "Error: exec failed: ", 0
str_18: db "", 10, "", 0
str_19: db "", 10, "", 0
str_20: db "╔════════════════════════════════════════════════╗", 10, "", 0
str_21: db "║  PoodillionOS Shell - Type-Aware Data Shell   ║", 10, "", 0
str_22: db "║                                                ║", 10, "", 0
str_23: db "║  • Type-safe binary pipelines                 ║", 10, "", 0
str_24: db "║  • Automatic schema detection                 ║", 10, "", 0
str_25: db "║  • Pretty table formatting                    ║", 10, "", 0
str_26: db "║                                                ║", 10, "", 0
str_27: db "║  Try: bin/ps | bin/where | bin/select         ║", 10, "", 0
str_28: db "╚════════════════════════════════════════════════╝", 10, "", 0
str_29: db "", 10, "", 0
str_30: db "psh> ", 0
str_31: db "exit", 0
str_32: db "quit", 0
str_33: db "Goodbye!", 0

section .text
global _start
global get_argc
global get_argv

section .bss
_startup_esp: resd 1

section .text

_start:
    mov [_startup_esp], esp  ; Save initial stack pointer
    call main
    ; Halt (infinite loop)
.halt:
    hlt
    jmp .halt

; get_argc() - returns argument count
get_argc:
    mov eax, [_startup_esp]
    mov eax, [eax]  ; argc is at [esp]
    ret

; get_argv(index) - returns pointer to argument string
get_argv:
    push ebp
    mov ebp, esp
    mov eax, [_startup_esp]
    mov ecx, [ebp+8]  ; index
    lea eax, [eax + 4 + ecx*4]  ; argv[index] = esp + 4 + index*4
    mov eax, [eax]
    pop ebp
    ret
    
print:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start0:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end1
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start0
while_end1:
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
print_return:
    mov esp, ebp
    pop ebp
    ret
    
println:
    push ebp
    mov ebp, esp
    mov eax, [ebp+8]
    push eax
    call print
    add esp, 4
    mov eax, 1
    push eax
    lea eax, [rel str_0]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
println_return:
    mov esp, ebp
    pop ebp
    ret
    
print_err:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start2:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end3
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start2
while_end3:
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 2
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
print_err_return:
    mov esp, ebp
    pop ebp
    ret
    
print_num:
    push ebp
    mov ebp, esp
    sub esp, 28
    mov eax, [ebp+8]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else5
    mov eax, 1
    push eax
    lea eax, [rel str_1]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    jmp print_num_return
    jmp endif4
else5:
endif4:
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-4]
    mov [ebp-12], eax
    mov eax, [ebp+8]
    mov [ebp-16], eax
    mov eax, 0
    mov [ebp-20], eax
while_start6:
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz while_end7
    mov eax, [ebp-16]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov eax, edx
    mov [ebp-24], eax
    mov eax, 48
    push eax
    mov eax, [ebp-24]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    mov eax, [ebp-12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-20], eax
    mov eax, [ebp-16]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov [ebp-16], eax
    jmp while_start6
while_end7:
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-28], eax
while_start8:
    mov eax, [ebp-28]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz while_end9
    mov eax, 1
    push eax
    mov eax, [ebp-28]
    mov ebx, eax
    mov eax, [ebp-12]
    add eax, ebx
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    mov eax, [ebp-28]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-28], eax
    jmp while_start8
while_end9:
print_num_return:
    mov esp, ebp
    pop ebp
    ret
    
strlen:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start10:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end11
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start10
while_end11:
    mov eax, [ebp-4]
    jmp strlen_return
strlen_return:
    mov esp, ebp
    pop ebp
    ret
    
strcmp:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start12:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end13
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    movzx eax, byte [eax]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else15
    mov eax, 1
    jmp strcmp_return
    jmp endif14
else15:
endif14:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start12
while_end13:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else17
    mov eax, 1
    jmp strcmp_return
    jmp endif16
else17:
endif16:
    mov eax, 0
    jmp strcmp_return
strcmp_return:
    mov esp, ebp
    pop ebp
    ret
    
strcpy:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start18:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end19
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start18
while_end19:
    mov eax, 0
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
strcpy_return:
    mov esp, ebp
    pop ebp
    ret
    
display_schema:
    push ebp
    mov ebp, esp
    sub esp, 8
    lea eax, [rel str_2]
    push eax
    call print
    add esp, 4
    lea eax, [rel str_3]
    push eax
    call print
    add esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start20:
    mov eax, [ebp-4]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end21
    mov eax, 1
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start20
while_end21:
    lea eax, [rel str_4]
    push eax
    call print
    add esp, 4
    mov eax, 4
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    call print_num
    add esp, 4
    lea eax, [rel str_5]
    push eax
    call print
    add esp, 4
    mov eax, 5
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    call print_num
    add esp, 4
    lea eax, [rel str_6]
    push eax
    call print
    add esp, 4
    mov eax, [ebp+8]
    push eax
    mov eax, 6
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-8]
    shl ebx, 1
    add eax, ebx
    movzx eax, word [eax]
    push eax
    call print_num
    add esp, 4
    lea eax, [rel str_7]
    push eax
    call print
    add esp, 4
display_schema_return:
    mov esp, ebp
    pop ebp
    ret
    
display_records:
    push ebp
    mov ebp, esp
    sub esp, 17
    lea eax, [rel str_8]
    push eax
    call print
    add esp, 4
    mov eax, [ebp+12]
    push eax
    call print_num
    add esp, 4
    lea eax, [rel str_9]
    push eax
    call print
    add esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start22:
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+12]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end23
    lea eax, [rel str_10]
    push eax
    call print
    add esp, 4
    mov eax, [ebp-4]
    push eax
    call print_num
    add esp, 4
    lea eax, [rel str_11]
    push eax
    call print
    add esp, 4
    mov eax, 12
    mov [ebp-8], eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else25
    mov eax, [ebp+16]
    mov [ebp-8], eax
    jmp endif24
else25:
endif24:
    mov eax, 0
    mov [ebp-12], eax
while_start26:
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end27
    mov eax, 12
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+16]
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    mov byte [ebp-13], al
    movzx eax, byte [ebp-13]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    mov ecx, ebx
    shr eax, cl
    mov byte [ebp-14], al
    movzx eax, byte [ebp-13]
    push eax
    mov eax, 15
    mov ebx, eax
    pop eax
    and eax, ebx
    mov byte [ebp-15], al
    mov eax, 48
    push eax
    movzx eax, byte [ebp-14]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov byte [ebp-16], al
    movzx eax, byte [ebp-14]
    push eax
    mov eax, 9
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else29
    mov eax, 97
    push eax
    movzx eax, byte [ebp-14]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov byte [ebp-16], al
    jmp endif28
else29:
endif28:
    mov eax, 48
    push eax
    movzx eax, byte [ebp-15]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov byte [ebp-17], al
    movzx eax, byte [ebp-15]
    push eax
    mov eax, 9
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else31
    mov eax, 97
    push eax
    movzx eax, byte [ebp-15]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov byte [ebp-17], al
    jmp endif30
else31:
endif30:
    mov eax, 1
    push eax
    lea eax, [ebp-16]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    mov eax, 1
    push eax
    lea eax, [ebp-17]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    mov eax, 1
    push eax
    lea eax, [rel str_12]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    jmp while_start26
while_end27:
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else33
    lea eax, [rel str_13]
    push eax
    call print
    add esp, 4
    jmp endif32
else33:
endif32:
    lea eax, [rel str_14]
    push eax
    call print
    add esp, 4
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start22
while_end23:
    lea eax, [rel str_15]
    push eax
    call print
    add esp, 4
display_records_return:
    mov esp, ebp
    pop ebp
    ret
    
trim_start:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start34:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz while_end35
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start34
while_end35:
    mov eax, [ebp+8]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    pop eax
    add eax, ebx
    jmp trim_start_return
trim_start_return:
    mov esp, ebp
    pop ebp
    ret
    
trim_end:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, [ebp+8]
    push eax
    call strlen
    add esp, 4
    mov [ebp-4], eax
while_start36:
    mov eax, [ebp-4]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz while_end37
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else39
    mov eax, 0
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-4], eax
    jmp endif38
else39:
    jmp trim_end_return
endif38:
    jmp while_start36
while_end37:
trim_end_return:
    mov esp, ebp
    pop ebp
    ret
    
find_pipe:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start40:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end41
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 124
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else43
    mov eax, [ebp-4]
    jmp find_pipe_return
    jmp endif42
else43:
endif42:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start40
while_end41:
    mov eax, 1
    neg eax
    jmp find_pipe_return
find_pipe_return:
    mov esp, ebp
    pop ebp
    ret
    
count_commands:
    push ebp
    mov ebp, esp
    sub esp, 8
    mov eax, 1
    mov [ebp-4], eax
    mov eax, 0
    mov [ebp-8], eax
while_start44:
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end45
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 124
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else47
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp endif46
else47:
endif46:
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    jmp while_start44
while_end45:
    mov eax, [ebp-4]
    jmp count_commands_return
count_commands_return:
    mov esp, ebp
    pop ebp
    ret
    
needs_dot_slash:
    push ebp
    mov ebp, esp
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 47
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else49
    mov eax, 0
    jmp needs_dot_slash_return
    jmp endif48
else49:
endif48:
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 46
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else51
    mov eax, 0
    jmp needs_dot_slash_return
    jmp endif50
else51:
endif50:
    mov eax, 1
    jmp needs_dot_slash_return
needs_dot_slash_return:
    mov esp, ebp
    pop ebp
    ret
    
make_exec_path:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, [ebp+8]
    push eax
    call needs_dot_slash
    add esp, 4
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else53
    mov eax, [ebp+8]
    push eax
    mov eax, [ebp+12]
    push eax
    call strcpy
    add esp, 8
    mov eax, [ebp+12]
    jmp make_exec_path_return
    jmp endif52
else53:
endif52:
    mov eax, 46
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 47
    push eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 0
    mov [ebp-4], eax
while_start54:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end55
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start54
while_end55:
    mov eax, 0
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp+12]
    jmp make_exec_path_return
make_exec_path_return:
    mov esp, ebp
    pop ebp
    ret
    
parse_args:
    push ebp
    mov ebp, esp
    sub esp, 16
    mov eax, 0
    mov [ebp-4], eax
    mov eax, 0
    mov [ebp-8], eax
    mov eax, 0
    mov [ebp-12], eax
while_start56:
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz while_end57
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    jmp while_start56
while_end57:
while_start58:
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end59
    mov eax, [ebp-12]
    mov [ebp-16], eax
while_start60:
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end61
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else63
    jmp while_end61
    jmp endif62
else63:
endif62:
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    jmp while_start60
while_end61:
    mov eax, 0
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+16]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
while_start64:
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz while_end65
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    jmp while_start64
while_end65:
    mov eax, [ebp-4]
    push eax
    mov eax, 15
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else67
    jmp while_end59
    jmp endif66
else67:
endif66:
    jmp while_start58
while_end59:
    mov eax, 0
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+16]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp-4]
    jmp parse_args_return
parse_args_return:
    mov esp, ebp
    pop ebp
    ret
    
exec_pipeline:
    push ebp
    mov ebp, esp
    sub esp, 144
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 32768
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-4]
    mov [ebp-12], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 8192
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-16], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 16384
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-20], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 16640
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-24], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 16896
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-28], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 17152
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-32], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 19200
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-36], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 27392
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-40], eax
    mov eax, 0
    mov [ebp-44], eax
    mov eax, 0
    mov [ebp-48], eax
    mov eax, 0
    mov [ebp-52], eax
    mov eax, [ebp-52]
    mov [ebp-56], eax
while_start68:
    mov eax, [ebp-48]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end69
    mov eax, [ebp-48]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 124
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else71
    mov eax, 0
    push eax
    mov eax, [ebp-52]
    mov ebx, eax
    mov eax, [ebp-16]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-52]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-52], eax
    mov eax, [ebp-16]
    push eax
    mov eax, [ebp-56]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    call trim_start
    add esp, 4
    mov [ebp-60], eax
    mov eax, [ebp-60]
    push eax
    call trim_end
    add esp, 4
    mov eax, [ebp-60]
    push eax
    mov eax, [ebp-44]
    mov ebx, eax
    mov eax, [ebp-28]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp-44]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-44], eax
    mov eax, [ebp-48]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-48], eax
while_start72:
    mov eax, [ebp-48]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz while_end73
    mov eax, [ebp-48]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-48], eax
    jmp while_start72
while_end73:
    mov eax, [ebp-52]
    mov [ebp-56], eax
    jmp endif70
else71:
    mov eax, [ebp-48]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, [ebp-52]
    mov ebx, eax
    mov eax, [ebp-16]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-52]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-52], eax
    mov eax, [ebp-48]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-48], eax
endif70:
    jmp while_start68
while_end69:
    mov eax, 0
    push eax
    mov eax, [ebp-52]
    mov ebx, eax
    mov eax, [ebp-16]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-16]
    push eax
    mov eax, [ebp-56]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    call trim_start
    add esp, 4
    mov [ebp-64], eax
    mov eax, [ebp-64]
    push eax
    call trim_end
    add esp, 4
    mov eax, [ebp-64]
    push eax
    mov eax, [ebp-44]
    mov ebx, eax
    mov eax, [ebp-28]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp-44]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-44], eax
    mov eax, [ebp-44]
    mov [ebp-68], eax
    mov eax, 0
    mov [ebp-72], eax
while_start74:
    mov eax, [ebp-72]
    push eax
    mov eax, [ebp-68]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end75
    mov eax, [ebp-72]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    mov eax, [ebp-20]
    shl ebx, 2
    add eax, ebx
    push eax
    mov eax, 42
    push eax
    call syscall1
    add esp, 8
    mov [ebp-76], eax
    mov eax, [ebp-76]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else77
    lea eax, [rel str_16]
    push eax
    call print_err
    add esp, 4
    jmp exec_pipeline_return
    jmp endif76
else77:
endif76:
    mov eax, [ebp-72]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-72], eax
    jmp while_start74
while_end75:
    mov eax, 0
    mov [ebp-72], eax
while_start78:
    mov eax, [ebp-72]
    push eax
    mov eax, [ebp-44]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end79
    mov eax, 0
    push eax
    mov eax, 2
    push eax
    call syscall1
    add esp, 8
    mov [ebp-80], eax
    mov eax, [ebp-80]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else81
    mov eax, [ebp-72]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else83
    mov eax, 0
    push eax
    mov eax, [ebp-72]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    mov eax, [ebp-20]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    push eax
    mov eax, 63
    push eax
    call syscall2
    add esp, 12
    jmp endif82
else83:
endif82:
    mov eax, 1
    push eax
    mov eax, [ebp-72]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-20]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    push eax
    mov eax, 63
    push eax
    call syscall2
    add esp, 12
    mov eax, 0
    mov [ebp-84], eax
while_start84:
    mov eax, [ebp-84]
    push eax
    mov eax, [ebp-68]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end85
    mov eax, [ebp-84]
    mov ebx, eax
    mov eax, [ebp-20]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-84]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-84], eax
    jmp while_start84
while_end85:
    mov eax, [ebp-36]
    push eax
    mov eax, [ebp-72]
    push eax
    mov eax, 1024
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-88], eax
    mov eax, [ebp-32]
    push eax
    mov eax, [ebp-72]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-92], eax
    mov eax, [ebp-92]
    push eax
    mov eax, [ebp-88]
    push eax
    mov eax, [ebp-72]
    mov ebx, eax
    mov eax, [ebp-28]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    push eax
    call parse_args
    add esp, 12
    mov [ebp-96], eax
    mov eax, [ebp-40]
    push eax
    mov eax, [ebp-72]
    push eax
    mov eax, 256
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-100], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-92]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    mov [ebp-104], eax
    mov eax, [ebp-100]
    push eax
    mov eax, [ebp-104]
    push eax
    call make_exec_path
    add esp, 8
    mov [ebp-108], eax
    mov eax, [ebp-108]
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-92]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 0
    push eax
    mov eax, [ebp-92]
    push eax
    mov eax, [ebp-108]
    push eax
    mov eax, 11
    push eax
    call syscall3
    add esp, 16
    lea eax, [rel str_17]
    push eax
    call print_err
    add esp, 4
    mov eax, [ebp-108]
    push eax
    call print_err
    add esp, 4
    lea eax, [rel str_18]
    push eax
    call print_err
    add esp, 4
    mov eax, 1
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
    jmp endif80
else81:
endif80:
    mov eax, [ebp-80]
    push eax
    mov eax, [ebp-72]
    mov ebx, eax
    mov eax, [ebp-24]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp-72]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-72], eax
    jmp while_start78
while_end79:
    mov eax, 0
    mov [ebp-72], eax
while_start86:
    mov eax, [ebp-72]
    push eax
    mov eax, [ebp-68]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end87
    mov eax, [ebp-72]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-20]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-72]
    push eax
    mov eax, [ebp-68]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else89
    mov eax, [ebp-72]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    mov eax, [ebp-20]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
    jmp endif88
else89:
endif88:
    mov eax, [ebp-72]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-72], eax
    jmp while_start86
while_end87:
    mov eax, [ebp-68]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    mov eax, [ebp-20]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    mov [ebp-112], eax
    mov eax, 4
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-112]
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-116], eax
    mov eax, [ebp-116]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else91
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-12]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 80
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else93
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-12]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 83
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else95
    mov eax, 2
    mov ebx, eax
    mov eax, [ebp-12]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 67
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else97
    mov eax, 3
    mov ebx, eax
    mov eax, [ebp-12]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 72
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else99
    mov eax, 8
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-112]
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-116], eax
    mov eax, [ebp-12]
    push eax
    call display_schema
    add esp, 4
    mov eax, [ebp-12]
    push eax
    mov eax, 6
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-120], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-120]
    shl ebx, 1
    add eax, ebx
    movzx eax, word [eax]
    mov [ebp-124], eax
    mov eax, [ebp-12]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-128], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-128]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    mov [ebp-132], eax
    mov eax, [ebp-132]
    push eax
    mov eax, [ebp-124]
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov [ebp-136], eax
    mov eax, [ebp-136]
    push eax
    mov eax, 8000
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else101
    mov eax, 8000
    mov [ebp-136], eax
    jmp endif100
else101:
endif100:
    mov eax, [ebp-136]
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 12
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-112]
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-116], eax
    mov eax, [ebp-124]
    push eax
    mov eax, [ebp-132]
    push eax
    mov eax, [ebp-12]
    push eax
    call display_records
    add esp, 12
    mov eax, [ebp-112]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
    mov eax, 0
    mov [ebp-72], eax
while_start102:
    mov eax, [ebp-72]
    push eax
    mov eax, [ebp-44]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end103
    mov eax, 0
    mov [ebp-140], eax
    mov eax, 0
    push eax
    lea eax, [ebp-140]
    push eax
    mov eax, [ebp-72]
    mov ebx, eax
    mov eax, [ebp-24]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    push eax
    mov eax, 7
    push eax
    call syscall3
    add esp, 16
    mov eax, [ebp-72]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-72], eax
    jmp while_start102
while_end103:
    jmp exec_pipeline_return
    jmp endif98
else99:
endif98:
    jmp endif96
else97:
endif96:
    jmp endif94
else95:
endif94:
    jmp endif92
else93:
endif92:
    jmp endif90
else91:
endif90:
    mov eax, [ebp-116]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else105
    mov eax, [ebp-116]
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    jmp endif104
else105:
endif104:
    mov eax, 8000
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-112]
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-116], eax
while_start106:
    mov eax, [ebp-116]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz while_end107
    mov eax, [ebp-116]
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
    mov eax, 8000
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-112]
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-116], eax
    jmp while_start106
while_end107:
    mov eax, [ebp-112]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
    mov eax, 0
    mov [ebp-72], eax
while_start108:
    mov eax, [ebp-72]
    push eax
    mov eax, [ebp-44]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end109
    mov eax, 0
    mov [ebp-144], eax
    mov eax, 0
    push eax
    lea eax, [ebp-144]
    push eax
    mov eax, [ebp-72]
    mov ebx, eax
    mov eax, [ebp-24]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    push eax
    mov eax, 7
    push eax
    call syscall3
    add esp, 16
    mov eax, [ebp-72]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-72], eax
    jmp while_start108
while_end109:
exec_pipeline_return:
    mov esp, ebp
    pop ebp
    ret
    
main:
    push ebp
    mov ebp, esp
    sub esp, 20
    lea eax, [rel str_19]
    push eax
    call print
    add esp, 4
    lea eax, [rel str_20]
    push eax
    call print
    add esp, 4
    lea eax, [rel str_21]
    push eax
    call print
    add esp, 4
    lea eax, [rel str_22]
    push eax
    call print
    add esp, 4
    lea eax, [rel str_23]
    push eax
    call print
    add esp, 4
    lea eax, [rel str_24]
    push eax
    call print
    add esp, 4
    lea eax, [rel str_25]
    push eax
    call print
    add esp, 4
    lea eax, [rel str_26]
    push eax
    call print
    add esp, 4
    lea eax, [rel str_27]
    push eax
    call print
    add esp, 4
    lea eax, [rel str_28]
    push eax
    call print
    add esp, 4
    lea eax, [rel str_29]
    push eax
    call print
    add esp, 4
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 4096
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-4]
    mov [ebp-12], eax
    mov eax, 1
    mov [ebp-16], eax
while_start110:
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end111
    lea eax, [rel str_30]
    push eax
    call print
    add esp, 4
    mov eax, 1024
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 0
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-20], eax
    mov eax, [ebp-20]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    test eax, eax
    jz else113
    mov eax, 0
    mov [ebp-16], eax
    jmp endif112
else113:
endif112:
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else115
    mov eax, [ebp-20]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else117
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov ebx, eax
    mov eax, [ebp-12]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else119
    mov eax, 0
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov ebx, eax
    mov eax, [ebp-12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-20], eax
    jmp endif118
else119:
    mov eax, 0
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    mov eax, [ebp-12]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
endif118:
    jmp endif116
else117:
endif116:
    mov eax, [ebp-20]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else121
    lea eax, [rel str_31]
    push eax
    mov eax, [ebp-12]
    push eax
    call strcmp
    add esp, 8
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else123
    mov eax, 0
    mov [ebp-16], eax
    jmp endif122
else123:
endif122:
    lea eax, [rel str_32]
    push eax
    mov eax, [ebp-12]
    push eax
    call strcmp
    add esp, 8
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else125
    mov eax, 0
    mov [ebp-16], eax
    jmp endif124
else125:
endif124:
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else127
    mov eax, [ebp-12]
    push eax
    call exec_pipeline
    add esp, 4
    jmp endif126
else127:
endif126:
    jmp endif120
else121:
endif120:
    jmp endif114
else115:
endif114:
    jmp while_start110
while_end111:
    lea eax, [rel str_33]
    push eax
    call println
    add esp, 4
    mov eax, 0
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
main_return:
    mov esp, ebp
    pop ebp
    ret
