; Generated by Mini-Nim Compiler
bits 32

section .text
global mininim_kernel_main

    
mininim_kernel_main:
    push ebp
    mov ebp, esp
    mov eax, 753664
    mov [ebp-4], eax
    mov eax, 0
    mov [ebp-8], eax
while_start0:
    mov eax, [ebp-8]
    push eax
    mov eax, 4000
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end1
    mov eax, 32
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp-8]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    mov eax, 80
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, 2
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, 3
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, 4
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, 5
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 100
    push eax
    mov eax, 6
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, 7
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 105
    push eax
    mov eax, 8
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, 9
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 108
    push eax
    mov eax, 10
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, 11
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 108
    push eax
    mov eax, 12
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, 13
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 105
    push eax
    mov eax, 14
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, 15
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, 16
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, 17
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 110
    push eax
    mov eax, 18
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, 19
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 79
    push eax
    mov eax, 20
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, 21
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 83
    push eax
    mov eax, 22
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, 23
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, 24
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, 25
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 118
    push eax
    mov eax, 26
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, 27
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 48
    push eax
    mov eax, 28
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, 29
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 46
    push eax
    mov eax, 30
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, 31
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 49
    push eax
    mov eax, 32
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, 33
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, 34
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, 35
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 45
    push eax
    mov eax, 36
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, 37
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, 38
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, 39
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 77
    push eax
    mov eax, 40
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, 41
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 105
    push eax
    mov eax, 42
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, 43
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 110
    push eax
    mov eax, 44
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, 45
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 105
    push eax
    mov eax, 46
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, 47
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 45
    push eax
    mov eax, 48
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, 49
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 78
    push eax
    mov eax, 50
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, 51
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 105
    push eax
    mov eax, 52
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, 53
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 109
    push eax
    mov eax, 54
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, 55
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, 56
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, 57
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 83
    push eax
    mov eax, 58
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 15
    push eax
    mov eax, 59
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 104
    push eax
    mov eax, 60
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 15
    push eax
    mov eax, 61
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 101
    push eax
    mov eax, 62
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 15
    push eax
    mov eax, 63
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 108
    push eax
    mov eax, 64
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 15
    push eax
    mov eax, 65
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 108
    push eax
    mov eax, 66
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 15
    push eax
    mov eax, 67
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 160
    mov [ebp-12], eax
    mov eax, 84
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 121
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 112
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 5
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 101
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 6
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 7
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 9
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 99
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 11
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 12
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 13
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 109
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 14
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 15
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 109
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 17
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 97
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 18
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 19
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 110
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 20
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 21
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 100
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 22
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 23
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 115
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 24
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 25
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 58
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 26
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 27
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 28
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 29
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 108
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 30
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 31
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 115
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 33
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 34
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 35
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 99
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 36
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 37
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 97
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 38
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 39
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 116
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 40
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 41
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 42
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 43
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 101
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 44
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 45
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 99
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 46
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 47
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 104
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 48
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 49
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 50
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 51
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 52
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 53
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 104
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 54
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 55
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 101
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 56
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 57
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 108
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 58
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 59
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 112
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 60
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 61
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 640
    mov [ebp-16], eax
    mov eax, 114
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 5
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 116
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 6
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 7
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 64
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 9
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 112
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 11
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 12
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 13
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 14
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 15
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 100
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 17
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 105
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 18
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 19
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 108
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 20
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 21
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 108
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 22
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 23
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 105
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 24
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 25
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 26
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 27
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 110
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 28
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 29
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 58
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 30
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 31
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 126
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 33
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 35
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 34
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 35
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 36
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 37
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 800
    mov [ebp-20], eax
    mov eax, 98
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 105
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 110
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 5
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 47
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 6
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 7
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 9
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 11
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 104
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 12
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 13
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 14
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 15
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 109
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 17
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 101
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 18
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 19
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 47
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 20
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 21
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 22
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 23
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 24
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 25
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 114
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 26
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 27
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 28
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 29
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 30
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 31
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 116
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 33
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 47
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 34
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 35
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 36
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 37
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 38
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 39
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 117
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 40
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 41
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 115
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 42
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 43
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 114
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 44
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 45
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 47
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 46
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 47
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 48
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 49
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 50
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 51
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 116
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 52
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 53
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 109
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 54
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 55
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 112
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 56
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 57
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 47
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 58
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 9
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 59
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 1120
    mov [ebp-24], eax
    mov eax, 87
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 15
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 101
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 15
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 108
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 15
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 5
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 99
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 6
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 15
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 7
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 15
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 9
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 109
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 15
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 11
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 101
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 12
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 15
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 13
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 14
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 15
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 116
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 15
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 17
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 18
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 15
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 19
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 20
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 21
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 80
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 22
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 23
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 24
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 25
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 26
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 27
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 100
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 28
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 29
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 105
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 30
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 31
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 108
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 33
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 108
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 34
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 35
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 105
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 36
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 37
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 38
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 39
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 110
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 40
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 41
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 79
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 42
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 43
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 83
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 44
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 45
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 33
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 46
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 15
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 47
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 1280
    mov [ebp-28], eax
    mov eax, 66
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 117
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 105
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 5
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 108
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 6
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 7
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 116
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 9
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 11
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 119
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 12
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 13
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 105
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 14
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 15
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 116
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 17
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 104
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 18
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 19
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 20
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 21
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 77
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 22
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 23
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 105
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 24
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 25
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 110
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 26
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 27
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 105
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 28
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 29
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 45
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 30
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 31
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 78
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 33
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 105
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 34
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 35
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 109
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 36
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 11
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 37
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 38
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 7
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 39
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 99
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 40
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 41
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 111
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 42
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 43
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 109
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 44
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 45
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 112
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 46
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 47
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 105
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 48
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 49
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 108
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 50
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 51
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 101
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 52
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 53
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 114
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 54
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 14
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, 55
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov [eax], ebx
while_start2:
    mov eax, 1
    test eax, eax
    jz while_end3
    jmp while_start2
while_end3:
    jmp while_start0
while_end1:
.return:
    mov esp, ebp
    pop ebp
    ret