; Generated by Mini-Nim Compiler
bits 32

extern serial_print

section .data
str_0: db "Hello from Mini-Nim!\n", 0
str_1: db "String literals work!\n", 0

section .text
global mininim_kernel_main

    
mininim_kernel_main:
    push ebp
    mov ebp, esp
    lea eax, [rel str_0]
    push eax
    call serial_print
    add esp, 4
    lea eax, [rel str_1]
    push eax
    call serial_print
    add esp, 4
while_start0:
    mov eax, 1
    test eax, eax
    jz while_end1
    jmp while_start0
while_end1:
.return:
    mov esp, ebp
    pop ebp
    ret