; Generated by Mini-Nim Compiler
bits 32

extern serial_print
extern serial_putchar

section .text
global mininim_kernel_main

    
mininim_kernel_main:
    push ebp
    mov ebp, esp
    mov eax, 69
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, 753664
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, 753665
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 88
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, 753666
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, 753667
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 84
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, 753668
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, 753669
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 33
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, 753670
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 10
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, 753671
    add eax, ebx
    pop ebx
    mov [eax], ebx
while_start0:
    mov eax, 1
    test eax, eax
    jz while_end1
    jmp while_start0
while_end1:
.return:
    mov esp, ebp
    pop ebp
    ret