; Generated by Brainhair Compiler
bits 32

section .text
global _start

_start:
    call main
    ; Halt (infinite loop)
.halt:
    hlt
    jmp .halt
    
main:
    push ebp
    mov ebp, esp
    mov eax, 753664
    mov [ebp-4], eax
    mov eax, 2
    mov [ebp-5], eax
    mov eax, 0
    mov [ebp-6], eax
    mov eax, [ebp-5]
    push eax
    mov eax, [ebp-6]
    mov ebx, eax
    pop eax
    or eax, ebx
    mov [ebp-7], eax
    mov eax, [ebp-6]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    mov ecx, ebx
    shl eax, cl
    mov [ebp-8], eax
    mov eax, [ebp-5]
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    or eax, ebx
    mov [ebp-9], eax
    mov eax, 753664
    mov [ebp-13], eax
.return:
    mov esp, ebp
    pop ebp
    ret