; Generated by Brainhair Compiler
bits 32

extern syscall1
extern syscall2
extern syscall3
extern syscall6
extern fast_memcpy

section .data
str_0: db "Terminal", 0
str_1: db "Files", 0
str_2: db "Editor", 0
str_3: db "Window", 0
str_4: db "Menu", 0
str_5: db "--timeout", 0
str_6: db "BDS starting with timeout: ", 0
str_7: db " seconds", 10, "", 0
str_8: db "/tmp/bds_drm.log", 0
str_9: db "/dev/dri/card0", 0
str_10: db "Error: Cannot open /dev/dri/card0", 10, "", 0
str_11: db "Falling back to fbdev...", 10, "", 0
str_12: db "DRM device opened: fd=", 0
str_13: db "", 10, "", 0
str_14: db "/dev/fb0", 0
str_15: db "Error: Cannot open /dev/fb0", 10, "", 0
str_16: db "Screen: ", 0
str_17: db "x", 0
str_18: db "", 10, "", 0
str_19: db "/dev/tty", 0
str_20: db "/dev/input/mice", 0
str_21: db "Timeout reached, exiting...", 10, "", 0

section .bss
g_timespec: resb 4

section .text
global _start
global get_argc
global get_argv

section .bss
_startup_esp: resd 1

section .text

_start:
    mov [_startup_esp], esp  ; Save initial stack pointer
    call main
    ; Exit with return code from main
    mov ebx, eax  ; Exit code
    mov eax, 1    ; sys_exit
    int 0x80

; get_argc() - returns argument count
get_argc:
    mov eax, [_startup_esp]
    mov eax, [eax]  ; argc is at [esp]
    ret

; get_argv(index) - returns pointer to argument string
get_argv:
    push ebp
    mov ebp, esp
    mov eax, [_startup_esp]
    mov ecx, [ebp+8]  ; index
    lea eax, [eax + 4 + ecx*4]  ; argv[index] = esp + 4 + index*4
    mov eax, [eax]
    pop ebp
    ret
    
print_str:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start0:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end1
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start0
while_end1:
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
print_str_return:
    mov esp, ebp
    pop ebp
    ret
    
print_num:
    push ebp
    mov ebp, esp
    sub esp, 29
    mov eax, 0
    mov [ebp-4], eax
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-8]
    mov [ebp-4], eax
    mov eax, [ebp+8]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else3
    mov eax, 48
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 0
    push eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-4]
    push eax
    call print_str
    add esp, 4
    jmp print_num_return
    jmp endif2
else3:
endif2:
    mov eax, 0
    mov [ebp-12], eax
    mov eax, [ebp+8]
    mov [ebp-16], eax
    mov eax, [ebp+8]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else5
    mov eax, 1
    mov [ebp-12], eax
    mov eax, 0
    push eax
    mov eax, [ebp+8]
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-16], eax
    jmp endif4
else5:
endif4:
    mov eax, 0
    mov [ebp-20], eax
while_start6:
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz while_end7
    mov eax, 48
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-16]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov [ebp-16], eax
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-20], eax
    jmp while_start6
while_end7:
    mov eax, [ebp-12]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else9
    mov eax, 45
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-20], eax
    jmp endif8
else9:
endif8:
    mov eax, 0
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 0
    mov [ebp-24], eax
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-28], eax
while_start10:
    mov eax, [ebp-24]
    push eax
    mov eax, [ebp-28]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end11
    mov eax, [ebp-24]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    movzx eax, byte [eax]
    mov byte [ebp-29], al
    mov eax, [ebp-28]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, [ebp-24]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    movzx eax, byte [ebp-29]
    push eax
    mov eax, [ebp-28]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-24]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-24], eax
    mov eax, [ebp-28]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-28], eax
    jmp while_start10
while_end11:
    mov eax, [ebp-4]
    push eax
    call print_str
    add esp, 4
print_num_return:
    mov esp, ebp
    pop ebp
    ret
    
atoi:
    push ebp
    mov ebp, esp
    sub esp, 8
    mov eax, 0
    mov [ebp-4], eax
    mov eax, 0
    mov [ebp-8], eax
while_start12:
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 48
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 57
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short14
    test ebx, ebx
    jz and_short14
    mov eax, 1
    jmp and_end15
and_short14:
    xor eax, eax
and_end15:
    test eax, eax
    jz while_end13
    mov eax, [ebp-4]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 48
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-4], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    jmp while_start12
while_end13:
    mov eax, [ebp-4]
    jmp atoi_return
atoi_return:
    mov esp, ebp
    pop ebp
    ret
    
streq:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start16:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short18
    test ebx, ebx
    jz and_short18
    mov eax, 1
    jmp and_end19
and_short18:
    xor eax, eax
and_end19:
    test eax, eax
    jz while_end17
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    movzx eax, byte [eax]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else21
    mov eax, 0
    jmp streq_return
    jmp endif20
else21:
endif20:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start16
while_end17:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+12]
    add eax, ebx
    movzx eax, byte [eax]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else23
    mov eax, 1
    jmp streq_return
    jmp endif22
else23:
endif22:
    mov eax, 0
    jmp streq_return
streq_return:
    mov esp, ebp
    pop ebp
    ret
    
get_time:
    push ebp
    mov ebp, esp
    mov eax, 0
    push eax
    mov eax, 13
    push eax
    call syscall1
    add esp, 8
    jmp get_time_return
get_time_return:
    mov esp, ebp
    pop ebp
    ret
    
sleep_ms:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, [rel g_timespec]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else25
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-4]
    mov [rel g_timespec], eax
    jmp endif24
else25:
endif24:
    mov eax, 0
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, [rel g_timespec]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp+8]
    push eax
    mov eax, 1000000
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, 1
    mov ebx, eax
    mov eax, [rel g_timespec]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 0
    push eax
    mov eax, [rel g_timespec]
    push eax
    mov eax, 162
    push eax
    call syscall2
    add esp, 12
sleep_ms_return:
    mov esp, ebp
    pop ebp
    ret
    
buf_pixel:
    push ebp
    mov ebp, esp
    mov eax, [ebp+12]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+24]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short28
    test ebx, ebx
    jz and_short28
    mov eax, 1
    jmp and_end29
and_short28:
    xor eax, eax
and_end29:
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short30
    test ebx, ebx
    jz and_short30
    mov eax, 1
    jmp and_end31
and_short30:
    xor eax, eax
and_end31:
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp+28]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short32
    test ebx, ebx
    jz and_short32
    mov eax, 1
    jmp and_end33
and_short32:
    xor eax, eax
and_end33:
    test eax, eax
    jz else27
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp+24]
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [ebp+12]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    jmp endif26
else27:
endif26:
buf_pixel_return:
    mov esp, ebp
    pop ebp
    ret
    
fill_rect:
    push ebp
    mov ebp, esp
    sub esp, 16
    mov eax, [ebp+16]
    mov [ebp-4], eax
while_start34:
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp+24]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end35
    mov eax, [ebp-4]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+36]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short38
    test ebx, ebx
    jz and_short38
    mov eax, 1
    jmp and_end39
and_short38:
    xor eax, eax
and_end39:
    test eax, eax
    jz else37
    mov eax, [ebp+12]
    mov [ebp-8], eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+20]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else41
    mov eax, 0
    mov [ebp-8], eax
    jmp endif40
else41:
endif40:
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp+32]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else43
    mov eax, [ebp+32]
    mov [ebp-12], eax
    jmp endif42
else43:
endif42:
    mov eax, [ebp-8]
    mov [ebp-16], eax
while_start44:
    mov eax, [ebp-16]
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end45
    mov eax, [ebp+28]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+32]
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp-16]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-16], eax
    jmp while_start44
while_end45:
    jmp endif36
else37:
endif36:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start34
while_end35:
fill_rect_return:
    mov esp, ebp
    pop ebp
    ret
    
get_font_row:
    push ebp
    mov ebp, esp
    mov eax, [ebp+8]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else47
    mov eax, 0
    jmp get_font_row_return
    jmp endif46
else47:
endif46:
    mov eax, [ebp+8]
    push eax
    mov eax, 65
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 90
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short50
    test ebx, ebx
    jz and_short50
    mov eax, 1
    jmp and_end51
and_short50:
    xor eax, eax
and_end51:
    test eax, eax
    jz else49
    mov eax, [ebp+12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, 5
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short54
    test ebx, ebx
    jz and_short54
    mov eax, 1
    jmp and_end55
and_short54:
    xor eax, eax
and_end55:
    test eax, eax
    jz else53
    mov eax, 126
    jmp get_font_row_return
    jmp endif52
else53:
endif52:
    mov eax, 0
    jmp get_font_row_return
    jmp endif48
else49:
endif48:
    mov eax, [ebp+8]
    push eax
    mov eax, 97
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 122
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short58
    test ebx, ebx
    jz and_short58
    mov eax, 1
    jmp and_end59
and_short58:
    xor eax, eax
and_end59:
    test eax, eax
    jz else57
    mov eax, [ebp+12]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, 6
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short62
    test ebx, ebx
    jz and_short62
    mov eax, 1
    jmp and_end63
and_short62:
    xor eax, eax
and_end63:
    test eax, eax
    jz else61
    mov eax, 126
    jmp get_font_row_return
    jmp endif60
else61:
endif60:
    mov eax, 0
    jmp get_font_row_return
    jmp endif56
else57:
endif56:
    mov eax, [ebp+8]
    push eax
    mov eax, 48
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 57
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short66
    test ebx, ebx
    jz and_short66
    mov eax, 1
    jmp and_end67
and_short66:
    xor eax, eax
and_end67:
    test eax, eax
    jz else65
    mov eax, [ebp+12]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, 6
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short70
    test ebx, ebx
    jz and_short70
    mov eax, 1
    jmp and_end71
and_short70:
    xor eax, eax
and_end71:
    test eax, eax
    jz else69
    mov eax, 60
    jmp get_font_row_return
    jmp endif68
else69:
endif68:
    mov eax, 0
    jmp get_font_row_return
    jmp endif64
else65:
endif64:
    mov eax, 0
    jmp get_font_row_return
get_font_row_return:
    mov esp, ebp
    pop ebp
    ret
    
draw_char:
    push ebp
    mov ebp, esp
    sub esp, 20
    mov eax, 0
    mov [ebp-4], eax
while_start72:
    mov eax, [ebp-4]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end73
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+20]
    push eax
    call get_font_row
    add esp, 8
    mov [ebp-8], eax
    mov eax, 0
    mov [ebp-12], eax
while_start74:
    mov eax, [ebp-12]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end75
    mov eax, [ebp-8]
    push eax
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov ebx, eax
    pop eax
    mov ecx, ebx
    shr eax, cl
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    and eax, ebx
    mov [ebp-16], eax
    mov eax, [ebp+28]
    mov [ebp-20], eax
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else77
    mov eax, [ebp+24]
    mov [ebp-20], eax
    jmp endif76
else77:
endif76:
    mov eax, [ebp+36]
    push eax
    mov eax, [ebp+32]
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+8]
    push eax
    call buf_pixel
    add esp, 24
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    jmp while_start74
while_end75:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start72
while_end73:
draw_char_return:
    mov esp, ebp
    pop ebp
    ret
    
draw_text:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start78:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+20]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+40]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short80
    test ebx, ebx
    jz and_short80
    mov eax, 1
    jmp and_end81
and_short80:
    xor eax, eax
and_end81:
    test eax, eax
    jz while_end79
    mov eax, [ebp+36]
    push eax
    mov eax, [ebp+32]
    push eax
    mov eax, [ebp+28]
    push eax
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+20]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+8]
    push eax
    call draw_char
    add esp, 32
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start78
while_end79:
draw_text_return:
    mov esp, ebp
    pop ebp
    ret
    
create_cursor_bo:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 64
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+12]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 64
    push eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp+12]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, 2
    mov ebx, eax
    mov eax, [ebp+12]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 0
    push eax
    mov eax, 3
    mov ebx, eax
    mov eax, [ebp+12]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp+12]
    push eax
    mov eax, 3223348402
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 54
    push eax
    call syscall3
    add esp, 16
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else83
    mov eax, 1
    neg eax
    jmp create_cursor_bo_return
    jmp endif82
else83:
endif82:
    mov eax, 0
    jmp create_cursor_bo_return
create_cursor_bo_return:
    mov esp, ebp
    pop ebp
    ret
    
draw_cursor_to_bo:
    push ebp
    mov ebp, esp
    sub esp, 12
    mov eax, 0
    mov [ebp-4], eax
while_start84:
    mov eax, [ebp-4]
    push eax
    mov eax, 64
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end85
    mov eax, 0
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start84
while_end85:
    mov eax, 0
    mov [ebp-4], eax
while_start86:
    mov eax, [ebp-4]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end87
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    mov eax, [ebp-4]
    mov [ebp-12], eax
    mov eax, [ebp-12]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short90
    test ebx, ebx
    jz and_short90
    mov eax, 1
    jmp and_end91
and_short90:
    xor eax, eax
and_end91:
    test eax, eax
    jz else89
    mov eax, 4278190080
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    jmp endif88
else89:
endif88:
    mov eax, [ebp-4]
    mov [ebp-8], eax
    mov eax, [ebp-12]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short94
    test ebx, ebx
    jz and_short94
    mov eax, 1
    jmp and_end95
and_short94:
    xor eax, eax
and_end95:
    test eax, eax
    jz else93
    mov eax, 4294967295
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    jmp endif92
else93:
endif92:
    mov eax, [ebp-4]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else97
    mov eax, [ebp-4]
    mov [ebp-8], eax
    mov eax, [ebp-4]
    mov [ebp-12], eax
    mov eax, [ebp-12]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short100
    test ebx, ebx
    jz and_short100
    mov eax, 1
    jmp and_end101
and_short100:
    xor eax, eax
and_end101:
    test eax, eax
    jz else99
    mov eax, 4294967295
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    jmp endif98
else99:
endif98:
    jmp endif96
else97:
endif96:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start86
while_end87:
draw_cursor_to_bo_return:
    mov esp, ebp
    pop ebp
    ret
    
set_hardware_cursor:
    push ebp
    mov ebp, esp
    sub esp, 8
    mov eax, 0
    mov [ebp-4], eax
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-8]
    mov [ebp-4], eax
    mov eax, 1
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    or eax, ebx
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp+12]
    push eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp+20]
    push eax
    mov eax, 2
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp+24]
    push eax
    mov eax, 3
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 64
    push eax
    mov eax, 4
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 64
    push eax
    mov eax, 5
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp+16]
    push eax
    mov eax, 6
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp-4]
    push eax
    mov eax, 3223086243
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 54
    push eax
    call syscall3
    add esp, 16
set_hardware_cursor_return:
    mov esp, ebp
    pop ebp
    ret
    
move_hardware_cursor:
    push ebp
    mov ebp, esp
    sub esp, 8
    mov eax, 0
    mov [ebp-4], eax
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-8]
    mov [ebp-4], eax
    mov eax, 2
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp+12]
    push eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp+16]
    push eax
    mov eax, 2
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp+20]
    push eax
    mov eax, 3
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 64
    push eax
    mov eax, 4
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 64
    push eax
    mov eax, 5
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 0
    push eax
    mov eax, 6
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp-4]
    push eax
    mov eax, 3223086243
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 54
    push eax
    call syscall3
    add esp, 16
move_hardware_cursor_return:
    mov esp, ebp
    pop ebp
    ret
    
window_ptr:
    push ebp
    mov ebp, esp
    mov eax, [ebp+8]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, 128
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    add eax, ebx
    jmp window_ptr_return
window_ptr_return:
    mov esp, ebp
    pop ebp
    ret
    
win_get:
    push ebp
    mov ebp, esp
    mov eax, [ebp+12]
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    jmp win_get_return
win_get_return:
    mov esp, ebp
    pop ebp
    ret
    
win_set:
    push ebp
    mov ebp, esp
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp+12]
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
win_set_return:
    mov esp, ebp
    pop ebp
    ret
    
get_window_title:
    push ebp
    mov ebp, esp
    mov eax, [ebp+8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else103
    lea eax, [rel str_0]
    jmp get_window_title_return
    jmp endif102
else103:
endif102:
    mov eax, [ebp+8]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else105
    lea eax, [rel str_1]
    jmp get_window_title_return
    jmp endif104
else105:
endif104:
    mov eax, [ebp+8]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else107
    lea eax, [rel str_2]
    jmp get_window_title_return
    jmp endif106
else107:
endif106:
    lea eax, [rel str_3]
    jmp get_window_title_return
get_window_title_return:
    mov esp, ebp
    pop ebp
    ret
    
create_window:
    push ebp
    mov ebp, esp
    sub esp, 8
    mov eax, 0
    mov [ebp-4], eax
while_start108:
    mov eax, [ebp-4]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end109
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    call window_ptr
    add esp, 8
    mov [ebp-8], eax
    mov eax, 0
    push eax
    mov eax, [ebp-8]
    push eax
    call win_get
    add esp, 8
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else111
    mov eax, 1
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp+12]
    push eax
    mov eax, 1
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp+16]
    push eax
    mov eax, 2
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp+20]
    push eax
    mov eax, 3
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp+24]
    push eax
    mov eax, 4
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, 1
    push eax
    mov eax, 5
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, 0
    push eax
    mov eax, 6
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, 0
    push eax
    mov eax, 7
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp+28]
    push eax
    mov eax, 8
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp+32]
    push eax
    mov eax, 9
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp+36]
    push eax
    mov eax, 11
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp-4]
    jmp create_window_return
    jmp endif110
else111:
endif110:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start108
while_end109:
    mov eax, 1
    neg eax
    jmp create_window_return
create_window_return:
    mov esp, ebp
    pop ebp
    ret
    
destroy_window:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, [ebp+12]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short114
    test ebx, ebx
    jz and_short114
    mov eax, 1
    jmp and_end115
and_short114:
    xor eax, eax
and_end115:
    test eax, eax
    jz else113
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call window_ptr
    add esp, 8
    mov [ebp-4], eax
    mov eax, 0
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp-4]
    push eax
    call win_set
    add esp, 12
    jmp endif112
else113:
endif112:
destroy_window_return:
    mov esp, ebp
    pop ebp
    ret
    
draw_decoration:
    push ebp
    mov ebp, esp
    sub esp, 28
    mov eax, 1
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-4], eax
    mov eax, 2
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-8], eax
    mov eax, 3
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-12], eax
    mov eax, 4
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-16], eax
    mov eax, 8
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-20], eax
    mov eax, 6316128
    mov [ebp-24], eax
    mov eax, [ebp+16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else117
    mov eax, 35071
    mov [ebp-24], eax
    mov eax, [ebp-20]
    push eax
    mov eax, 2105376
    mov ebx, eax
    pop eax
    or eax, ebx
    mov [ebp-20], eax
    jmp endif116
else117:
endif116:
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 3
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 3
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 3
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 3
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 24
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 3
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, 11
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    push eax
    call get_window_title
    add esp, 4
    mov [ebp-28], eax
    mov eax, 20
    push eax
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 16777215
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+8]
    push eax
    call draw_text
    add esp, 36
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, 14500932
    push eax
    mov eax, 16
    push eax
    mov eax, 16
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, 14540100
    push eax
    mov eax, 16
    push eax
    mov eax, 16
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, 16
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
draw_decoration_return:
    mov esp, ebp
    pop ebp
    ret
    
draw_window_body:
    push ebp
    mov ebp, esp
    sub esp, 20
    mov eax, 1
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-4], eax
    mov eax, 2
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-8], eax
    mov eax, 3
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-12], eax
    mov eax, 4
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-16], eax
    mov eax, 9
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-20], eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 3
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, 24
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 3
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 24
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
draw_window_body_return:
    mov esp, ebp
    pop ebp
    ret
    
composite:
    push ebp
    mov ebp, esp
    sub esp, 12
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+28]
    push eax
    mov eax, [ebp+24]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, 0
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, 0
    mov [ebp-4], eax
while_start118:
    mov eax, [ebp-4]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end119
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+16]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else121
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+12]
    push eax
    call window_ptr
    add esp, 8
    mov [ebp-8], eax
    mov eax, 0
    push eax
    mov eax, [ebp-8]
    push eax
    call win_get
    add esp, 8
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    push eax
    mov eax, 7
    push eax
    mov eax, [ebp-8]
    push eax
    call win_get
    add esp, 8
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short124
    test ebx, ebx
    jz and_short124
    mov eax, 1
    jmp and_end125
and_short124:
    xor eax, eax
and_end125:
    test eax, eax
    jz else123
    mov eax, 5
    push eax
    mov eax, [ebp-8]
    push eax
    call win_get
    add esp, 8
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else127
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp+8]
    push eax
    call draw_decoration
    add esp, 20
    jmp endif126
else127:
endif126:
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp+8]
    push eax
    call draw_window_body
    add esp, 16
    jmp endif122
else123:
endif122:
    jmp endif120
else121:
endif120:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start118
while_end119:
    mov eax, [ebp+16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short130
    test ebx, ebx
    jz and_short130
    mov eax, 1
    jmp and_end131
and_short130:
    xor eax, eax
and_end131:
    test eax, eax
    jz else129
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp+12]
    push eax
    call window_ptr
    add esp, 8
    mov [ebp-12], eax
    mov eax, 0
    push eax
    mov eax, [ebp-12]
    push eax
    call win_get
    add esp, 8
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    push eax
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    call win_get
    add esp, 8
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short134
    test ebx, ebx
    jz and_short134
    mov eax, 1
    jmp and_end135
and_short134:
    xor eax, eax
and_end135:
    test eax, eax
    jz else133
    mov eax, 5
    push eax
    mov eax, [ebp-12]
    push eax
    call win_get
    add esp, 8
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else137
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, 1
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp+8]
    push eax
    call draw_decoration
    add esp, 20
    jmp endif136
else137:
endif136:
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp+8]
    push eax
    call draw_window_body
    add esp, 16
    jmp endif132
else133:
endif132:
    jmp endif128
else129:
endif128:
composite_return:
    mov esp, ebp
    pop ebp
    ret
    
draw_taskbar:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, [ebp+20]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-4], eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, 2960685
    push eax
    mov eax, 32
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, 5263440
    push eax
    mov eax, 1
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, 26282
    push eax
    mov eax, 32
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, 80
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 4
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, 10
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, 26282
    push eax
    mov eax, 16777215
    push eax
    lea eax, [rel str_4]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 12
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 20
    push eax
    mov eax, [ebp+8]
    push eax
    call draw_text
    add esp, 36
draw_taskbar_return:
    mov esp, ebp
    pop ebp
    ret
    
main:
    push ebp
    mov ebp, esp
    sub esp, 188
    mov eax, 0
    mov [ebp-4], eax
    call get_argc
    mov [ebp-8], eax
    mov eax, 1
    mov [ebp-12], eax
while_start138:
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end139
    mov eax, [ebp-12]
    push eax
    call get_argv
    add esp, 4
    mov [ebp-16], eax
    lea eax, [rel str_5]
    push eax
    mov eax, [ebp-16]
    push eax
    call streq
    add esp, 8
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else141
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else143
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    call get_argv
    add esp, 4
    mov [ebp-20], eax
    mov eax, [ebp-20]
    push eax
    call atoi
    add esp, 4
    mov [ebp-4], eax
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    jmp endif142
else143:
endif142:
    jmp endif140
else141:
endif140:
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    jmp while_start138
while_end139:
    call get_time
    mov [ebp-24], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else145
    lea eax, [rel str_6]
    push eax
    call print_str
    add esp, 4
    mov eax, [ebp-4]
    push eax
    call print_num
    add esp, 4
    lea eax, [rel str_7]
    push eax
    call print_str
    add esp, 4
    jmp endif144
else145:
endif144:
    mov eax, 420
    push eax
    mov eax, 66
    push eax
    lea eax, [rel str_8]
    push eax
    mov eax, 5
    push eax
    call syscall3
    add esp, 16
    mov [ebp-28], eax
    mov eax, 2
    push eax
    lea eax, [rel str_9]
    push eax
    mov eax, 5
    push eax
    call syscall2
    add esp, 12
    mov [ebp-32], eax
    mov eax, [ebp-32]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else147
    lea eax, [rel str_10]
    push eax
    call print_str
    add esp, 4
    lea eax, [rel str_11]
    push eax
    call print_str
    add esp, 4
    mov eax, 1
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
    jmp endif146
else147:
endif146:
    lea eax, [rel str_12]
    push eax
    call print_str
    add esp, 4
    mov eax, [ebp-32]
    push eax
    call print_num
    add esp, 4
    lea eax, [rel str_13]
    push eax
    call print_str
    add esp, 4
    mov eax, 2
    push eax
    lea eax, [rel str_14]
    push eax
    mov eax, 5
    push eax
    call syscall2
    add esp, 12
    mov [ebp-36], eax
    mov eax, [ebp-36]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else149
    lea eax, [rel str_15]
    push eax
    call print_str
    add esp, 4
    mov eax, 1
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
    jmp endif148
else149:
endif148:
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-40], eax
    mov eax, [ebp-40]
    push eax
    mov eax, 8192
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-40]
    mov [ebp-44], eax
    mov eax, [ebp-40]
    push eax
    mov eax, 256
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-48], eax
    mov eax, [ebp-40]
    push eax
    mov eax, 512
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-52], eax
    mov eax, [ebp-40]
    push eax
    mov eax, 4096
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-56], eax
    mov eax, 17920
    mov [ebp-60], eax
    mov eax, [ebp-44]
    push eax
    mov eax, [ebp-60]
    push eax
    mov eax, [ebp-36]
    push eax
    mov eax, 54
    push eax
    call syscall3
    add esp, 16
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-44]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    mov [ebp-64], eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-44]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    mov [ebp-68], eax
    lea eax, [rel str_16]
    push eax
    call print_str
    add esp, 4
    mov eax, [ebp-64]
    push eax
    call print_num
    add esp, 4
    lea eax, [rel str_17]
    push eax
    call print_str
    add esp, 4
    mov eax, [ebp-68]
    push eax
    call print_num
    add esp, 4
    lea eax, [rel str_18]
    push eax
    call print_str
    add esp, 4
    mov eax, [ebp-56]
    push eax
    mov eax, [ebp-32]
    push eax
    call create_cursor_bo
    add esp, 8
    mov [ebp-72], eax
    mov eax, 0
    mov [ebp-76], eax
    mov eax, 0
    mov [ebp-80], eax
    mov eax, 0
    mov [ebp-84], eax
    mov eax, [ebp-72]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else151
    mov eax, 3
    mov ebx, eax
    mov eax, [ebp-56]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    mov [ebp-80], eax
    mov eax, 41
    mov [ebp-84], eax
    mov eax, 1
    mov [ebp-76], eax
    jmp endif150
else151:
endif150:
    mov eax, 2
    push eax
    lea eax, [rel str_19]
    push eax
    mov eax, 5
    push eax
    call syscall2
    add esp, 12
    mov [ebp-88], eax
    mov eax, [ebp-64]
    push eax
    mov eax, [ebp-68]
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov [ebp-92], eax
    mov eax, 0
    push eax
    mov eax, [ebp-36]
    push eax
    mov eax, 1
    push eax
    mov eax, 1
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    or eax, ebx
    push eax
    mov eax, [ebp-92]
    push eax
    mov eax, 0
    push eax
    mov eax, 192
    push eax
    call syscall6
    add esp, 28
    mov [ebp-96], eax
    mov eax, 0
    mov [ebp-100], eax
    mov eax, [ebp-96]
    mov [ebp-104], eax
    mov eax, [ebp-104]
    push eax
    mov eax, 4294963200
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else153
    mov eax, [ebp-96]
    mov [ebp-100], eax
    jmp endif152
else153:
    mov eax, 1
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
endif152:
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-108], eax
    mov eax, [ebp-108]
    push eax
    mov eax, [ebp-92]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 4096
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-108]
    mov [ebp-112], eax
    mov eax, 2
    push eax
    lea eax, [rel str_20]
    push eax
    mov eax, 5
    push eax
    call syscall2
    add esp, 12
    mov [ebp-116], eax
    mov eax, [ebp-116]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else155
    mov eax, 1
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
    jmp endif154
else155:
endif154:
    mov eax, 3
    push eax
    mov eax, [ebp-116]
    push eax
    mov eax, 55
    push eax
    call syscall2
    add esp, 12
    mov [ebp-120], eax
    mov eax, [ebp-120]
    push eax
    mov eax, 2048
    mov ebx, eax
    pop eax
    or eax, ebx
    push eax
    mov eax, 4
    push eax
    mov eax, [ebp-116]
    push eax
    mov eax, 55
    push eax
    call syscall3
    add esp, 16
    mov eax, 0
    mov [ebp-124], eax
while_start156:
    mov eax, [ebp-124]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end157
    mov eax, [ebp-124]
    push eax
    mov eax, [ebp-52]
    push eax
    call window_ptr
    add esp, 8
    mov [ebp-128], eax
    mov eax, 0
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp-128]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp-124]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-124], eax
    jmp while_start156
while_end157:
    mov eax, 1
    push eax
    mov eax, 15263976
    push eax
    mov eax, 2250154
    push eax
    mov eax, 250
    push eax
    mov eax, 350
    push eax
    mov eax, 60
    push eax
    mov eax, 80
    push eax
    mov eax, [ebp-52]
    push eax
    call create_window
    add esp, 32
    mov eax, 2
    push eax
    mov eax, 15790320
    push eax
    mov eax, 2271829
    push eax
    mov eax, 280
    push eax
    mov eax, 380
    push eax
    mov eax, 140
    push eax
    mov eax, 250
    push eax
    mov eax, [ebp-52]
    push eax
    call create_window
    add esp, 32
    mov eax, 3
    push eax
    mov eax, 15658734
    push eax
    mov eax, 11162914
    push eax
    mov eax, 240
    push eax
    mov eax, 320
    push eax
    mov eax, 100
    push eax
    mov eax, 450
    push eax
    mov eax, [ebp-52]
    push eax
    call create_window
    add esp, 32
    mov [ebp-132], eax
    mov eax, [ebp-64]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov [ebp-136], eax
    mov eax, [ebp-68]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov [ebp-140], eax
    mov eax, 1718874
    mov [ebp-144], eax
    mov eax, [ebp-132]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else159
    mov eax, [ebp-132]
    push eax
    mov eax, [ebp-52]
    push eax
    call window_ptr
    add esp, 8
    mov [ebp-148], eax
    mov eax, 1
    push eax
    mov eax, 6
    push eax
    mov eax, [ebp-148]
    push eax
    call win_set
    add esp, 12
    jmp endif158
else159:
endif158:
    mov eax, [ebp-144]
    push eax
    mov eax, [ebp-68]
    push eax
    mov eax, [ebp-64]
    push eax
    mov eax, [ebp-132]
    push eax
    mov eax, [ebp-52]
    push eax
    mov eax, [ebp-100]
    push eax
    call composite
    add esp, 24
    mov eax, [ebp-68]
    push eax
    mov eax, [ebp-64]
    push eax
    mov eax, [ebp-52]
    push eax
    mov eax, [ebp-100]
    push eax
    call draw_taskbar
    add esp, 16
    mov eax, [ebp-76]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else161
    mov eax, [ebp-140]
    push eax
    mov eax, [ebp-136]
    push eax
    mov eax, [ebp-80]
    push eax
    mov eax, [ebp-84]
    push eax
    mov eax, [ebp-32]
    push eax
    call set_hardware_cursor
    add esp, 20
    jmp endif160
else161:
endif160:
    mov eax, [ebp-144]
    push eax
    mov eax, [ebp-68]
    push eax
    mov eax, [ebp-64]
    push eax
    mov eax, [ebp-132]
    push eax
    mov eax, [ebp-52]
    push eax
    mov eax, [ebp-112]
    push eax
    call composite
    add esp, 24
    mov eax, [ebp-68]
    push eax
    mov eax, [ebp-64]
    push eax
    mov eax, [ebp-52]
    push eax
    mov eax, [ebp-112]
    push eax
    call draw_taskbar
    add esp, 16
    mov eax, [ebp-68]
    push eax
    mov eax, [ebp-64]
    push eax
    mov eax, 16777215
    push eax
    mov eax, 16
    push eax
    mov eax, 2
    push eax
    mov eax, [ebp-140]
    push eax
    mov eax, [ebp-136]
    push eax
    mov eax, [ebp-112]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp-68]
    push eax
    mov eax, [ebp-64]
    push eax
    mov eax, 16777215
    push eax
    mov eax, 2
    push eax
    mov eax, 12
    push eax
    mov eax, [ebp-140]
    push eax
    mov eax, [ebp-136]
    push eax
    mov eax, [ebp-112]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp-92]
    push eax
    mov eax, [ebp-112]
    push eax
    mov eax, [ebp-100]
    push eax
    call fast_memcpy
    add esp, 12
    mov eax, 1
    mov [ebp-152], eax
    mov eax, 0
    mov [ebp-156], eax
while_start162:
    mov eax, [ebp-152]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end163
    mov eax, [ebp-156]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-156], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else165
    call get_time
    mov [ebp-160], eax
    mov eax, [ebp-160]
    push eax
    mov eax, [ebp-24]
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else167
    lea eax, [rel str_21]
    push eax
    call print_str
    add esp, 4
    mov eax, 0
    mov [ebp-152], eax
    jmp endif166
else167:
endif166:
    jmp endif164
else165:
endif164:
    mov eax, 0
    mov [ebp-164], eax
    mov eax, 0
    mov [ebp-168], eax
    mov eax, 0
    mov [ebp-172], eax
    mov eax, 4
    push eax
    mov eax, [ebp-48]
    push eax
    mov eax, [ebp-116]
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-176], eax
while_start168:
    mov eax, [ebp-176]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz while_end169
    mov eax, 1
    mov [ebp-172], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-48]
    add eax, ebx
    movzx eax, byte [eax]
    mov [ebp-180], eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-48]
    add eax, ebx
    movzx eax, byte [eax]
    mov [ebp-184], eax
    mov eax, 2
    mov ebx, eax
    mov eax, [ebp-48]
    add eax, ebx
    movzx eax, byte [eax]
    mov [ebp-188], eax
    mov eax, [ebp-180]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    and eax, ebx
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else171
    mov eax, [ebp-184]
    push eax
    mov eax, 256
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-184], eax
    jmp endif170
else171:
endif170:
    mov eax, [ebp-180]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    and eax, ebx
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else173
    mov eax, [ebp-188]
    push eax
    mov eax, 256
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-188], eax
    jmp endif172
else173:
endif172:
    mov eax, [ebp-164]
    push eax
    mov eax, [ebp-184]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-164], eax
    mov eax, [ebp-168]
    push eax
    mov eax, [ebp-188]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-168], eax
    mov eax, 4
    push eax
    mov eax, [ebp-48]
    push eax
    mov eax, [ebp-116]
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-176], eax
    jmp while_start168
while_end169:
    mov eax, [ebp-172]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else175
    mov eax, [ebp-136]
    push eax
    mov eax, [ebp-164]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-136], eax
    mov eax, [ebp-140]
    push eax
    mov eax, [ebp-168]
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-140], eax
    mov eax, [ebp-136]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else177
    mov eax, 0
    mov [ebp-136], eax
    jmp endif176
else177:
endif176:
    mov eax, [ebp-136]
    push eax
    mov eax, [ebp-64]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else179
    mov eax, [ebp-64]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-136], eax
    jmp endif178
else179:
endif178:
    mov eax, [ebp-140]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else181
    mov eax, 0
    mov [ebp-140], eax
    jmp endif180
else181:
endif180:
    mov eax, [ebp-140]
    push eax
    mov eax, [ebp-68]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else183
    mov eax, [ebp-68]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-140], eax
    jmp endif182
else183:
endif182:
    jmp endif174
else175:
endif174:
    mov eax, [ebp-144]
    push eax
    mov eax, [ebp-68]
    push eax
    mov eax, [ebp-64]
    push eax
    mov eax, [ebp-132]
    push eax
    mov eax, [ebp-52]
    push eax
    mov eax, [ebp-112]
    push eax
    call composite
    add esp, 24
    mov eax, [ebp-68]
    push eax
    mov eax, [ebp-64]
    push eax
    mov eax, [ebp-52]
    push eax
    mov eax, [ebp-112]
    push eax
    call draw_taskbar
    add esp, 16
    mov eax, [ebp-68]
    push eax
    mov eax, [ebp-64]
    push eax
    mov eax, 16777215
    push eax
    mov eax, 16
    push eax
    mov eax, 2
    push eax
    mov eax, [ebp-140]
    push eax
    mov eax, [ebp-136]
    push eax
    mov eax, [ebp-112]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp-68]
    push eax
    mov eax, [ebp-64]
    push eax
    mov eax, 16777215
    push eax
    mov eax, 2
    push eax
    mov eax, 12
    push eax
    mov eax, [ebp-140]
    push eax
    mov eax, [ebp-136]
    push eax
    mov eax, [ebp-112]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp-92]
    push eax
    mov eax, [ebp-112]
    push eax
    mov eax, [ebp-100]
    push eax
    call fast_memcpy
    add esp, 12
    jmp while_start162
while_end163:
    mov eax, [ebp-88]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else185
    mov eax, [ebp-88]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
    jmp endif184
else185:
endif184:
    mov eax, [ebp-32]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-36]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-116]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
    mov eax, 0
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
main_return:
    mov esp, ebp
    pop ebp
    ret
