; Generated by Brainhair Compiler
bits 32

extern syscall1
extern syscall2
extern syscall3
extern syscall6
extern fast_memcpy

section .data
str_0: db "Terminal", 0
str_1: db "Files", 0
str_2: db "Editor", 0
str_3: db "Window", 0
str_4: db "Menu", 0
str_5: db "/tmp/bds_drm.log", 0
str_6: db "/dev/dri/card0", 0
str_7: db "Error: Cannot open /dev/dri/card0", 10, "", 0
str_8: db "Falling back to fbdev...", 10, "", 0
str_9: db "DRM device opened: fd=", 0
str_10: db "", 10, "", 0
str_11: db "/dev/fb0", 0
str_12: db "Error: Cannot open /dev/fb0", 10, "", 0
str_13: db "Screen: ", 0
str_14: db "x", 0
str_15: db "", 10, "", 0
str_16: db "/dev/tty", 0
str_17: db "/dev/input/mice", 0

section .text
global _start
global get_argc
global get_argv

section .bss
_startup_esp: resd 1

section .text

_start:
    mov [_startup_esp], esp  ; Save initial stack pointer
    call main
    ; Exit with return code from main
    mov ebx, eax  ; Exit code
    mov eax, 1    ; sys_exit
    int 0x80

; get_argc() - returns argument count
get_argc:
    mov eax, [_startup_esp]
    mov eax, [eax]  ; argc is at [esp]
    ret

; get_argv(index) - returns pointer to argument string
get_argv:
    push ebp
    mov ebp, esp
    mov eax, [_startup_esp]
    mov ecx, [ebp+8]  ; index
    lea eax, [eax + 4 + ecx*4]  ; argv[index] = esp + 4 + index*4
    mov eax, [eax]
    pop ebp
    ret
    
print_str:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start0:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end1
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start0
while_end1:
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 1
    push eax
    mov eax, 4
    push eax
    call syscall3
    add esp, 16
print_str_return:
    mov esp, ebp
    pop ebp
    ret
    
print_num:
    push ebp
    mov ebp, esp
    sub esp, 29
    mov eax, 0
    mov [ebp-4], eax
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-8]
    mov [ebp-4], eax
    mov eax, [ebp+8]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else3
    mov eax, 48
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 0
    push eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-4]
    push eax
    call print_str
    add esp, 4
    jmp print_num_return
    jmp endif2
else3:
endif2:
    mov eax, 0
    mov [ebp-12], eax
    mov eax, [ebp+8]
    mov [ebp-16], eax
    mov eax, [ebp+8]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else5
    mov eax, 1
    mov [ebp-12], eax
    mov eax, 0
    push eax
    mov eax, [ebp+8]
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-16], eax
    jmp endif4
else5:
endif4:
    mov eax, 0
    mov [ebp-20], eax
while_start6:
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz while_end7
    mov eax, 48
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-16]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov [ebp-16], eax
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-20], eax
    jmp while_start6
while_end7:
    mov eax, [ebp-12]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else9
    mov eax, 45
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-20], eax
    jmp endif8
else9:
endif8:
    mov eax, 0
    push eax
    mov eax, [ebp-20]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, 0
    mov [ebp-24], eax
    mov eax, [ebp-20]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-28], eax
while_start10:
    mov eax, [ebp-24]
    push eax
    mov eax, [ebp-28]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end11
    mov eax, [ebp-24]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    movzx eax, byte [eax]
    mov byte [ebp-29], al
    mov eax, [ebp-28]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, [ebp-24]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    movzx eax, byte [ebp-29]
    push eax
    mov eax, [ebp-28]
    mov ebx, eax
    mov eax, [ebp-4]
    add eax, ebx
    pop ebx
    mov byte [eax], bl
    mov eax, [ebp-24]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-24], eax
    mov eax, [ebp-28]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-28], eax
    jmp while_start10
while_end11:
    mov eax, [ebp-4]
    push eax
    call print_str
    add esp, 4
print_num_return:
    mov esp, ebp
    pop ebp
    ret
    
buf_pixel:
    push ebp
    mov ebp, esp
    mov eax, [ebp+12]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+24]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short14
    test ebx, ebx
    jz and_short14
    mov eax, 1
    jmp and_end15
and_short14:
    xor eax, eax
and_end15:
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short16
    test ebx, ebx
    jz and_short16
    mov eax, 1
    jmp and_end17
and_short16:
    xor eax, eax
and_end17:
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp+28]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short18
    test ebx, ebx
    jz and_short18
    mov eax, 1
    jmp and_end19
and_short18:
    xor eax, eax
and_end19:
    test eax, eax
    jz else13
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp+24]
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [ebp+12]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    jmp endif12
else13:
endif12:
buf_pixel_return:
    mov esp, ebp
    pop ebp
    ret
    
fill_rect:
    push ebp
    mov ebp, esp
    sub esp, 16
    mov eax, [ebp+16]
    mov [ebp-4], eax
while_start20:
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp+24]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end21
    mov eax, [ebp-4]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+36]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short24
    test ebx, ebx
    jz and_short24
    mov eax, 1
    jmp and_end25
and_short24:
    xor eax, eax
and_end25:
    test eax, eax
    jz else23
    mov eax, [ebp+12]
    mov [ebp-8], eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+20]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else27
    mov eax, 0
    mov [ebp-8], eax
    jmp endif26
else27:
endif26:
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp+32]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setg al
    movzx eax, al
    test eax, eax
    jz else29
    mov eax, [ebp+32]
    mov [ebp-12], eax
    jmp endif28
else29:
endif28:
    mov eax, [ebp-8]
    mov [ebp-16], eax
while_start30:
    mov eax, [ebp-16]
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end31
    mov eax, [ebp+28]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+32]
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp-16]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-16], eax
    jmp while_start30
while_end31:
    jmp endif22
else23:
endif22:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start20
while_end21:
fill_rect_return:
    mov esp, ebp
    pop ebp
    ret
    
get_font_row:
    push ebp
    mov ebp, esp
    mov eax, [ebp+8]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else33
    mov eax, 0
    jmp get_font_row_return
    jmp endif32
else33:
endif32:
    mov eax, [ebp+8]
    push eax
    mov eax, 65
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 90
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short36
    test ebx, ebx
    jz and_short36
    mov eax, 1
    jmp and_end37
and_short36:
    xor eax, eax
and_end37:
    test eax, eax
    jz else35
    mov eax, [ebp+12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, 5
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short40
    test ebx, ebx
    jz and_short40
    mov eax, 1
    jmp and_end41
and_short40:
    xor eax, eax
and_end41:
    test eax, eax
    jz else39
    mov eax, 126
    jmp get_font_row_return
    jmp endif38
else39:
endif38:
    mov eax, 0
    jmp get_font_row_return
    jmp endif34
else35:
endif34:
    mov eax, [ebp+8]
    push eax
    mov eax, 97
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 122
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short44
    test ebx, ebx
    jz and_short44
    mov eax, 1
    jmp and_end45
and_short44:
    xor eax, eax
and_end45:
    test eax, eax
    jz else43
    mov eax, [ebp+12]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, 6
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short48
    test ebx, ebx
    jz and_short48
    mov eax, 1
    jmp and_end49
and_short48:
    xor eax, eax
and_end49:
    test eax, eax
    jz else47
    mov eax, 126
    jmp get_font_row_return
    jmp endif46
else47:
endif46:
    mov eax, 0
    jmp get_font_row_return
    jmp endif42
else43:
endif42:
    mov eax, [ebp+8]
    push eax
    mov eax, 48
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 57
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short52
    test ebx, ebx
    jz and_short52
    mov eax, 1
    jmp and_end53
and_short52:
    xor eax, eax
and_end53:
    test eax, eax
    jz else51
    mov eax, [ebp+12]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, 6
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setle al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short56
    test ebx, ebx
    jz and_short56
    mov eax, 1
    jmp and_end57
and_short56:
    xor eax, eax
and_end57:
    test eax, eax
    jz else55
    mov eax, 60
    jmp get_font_row_return
    jmp endif54
else55:
endif54:
    mov eax, 0
    jmp get_font_row_return
    jmp endif50
else51:
endif50:
    mov eax, 0
    jmp get_font_row_return
get_font_row_return:
    mov esp, ebp
    pop ebp
    ret
    
draw_char:
    push ebp
    mov ebp, esp
    sub esp, 20
    mov eax, 0
    mov [ebp-4], eax
while_start58:
    mov eax, [ebp-4]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end59
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+20]
    push eax
    call get_font_row
    add esp, 8
    mov [ebp-8], eax
    mov eax, 0
    mov [ebp-12], eax
while_start60:
    mov eax, [ebp-12]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end61
    mov eax, [ebp-8]
    push eax
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov ebx, eax
    pop eax
    mov ecx, ebx
    shr eax, cl
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    and eax, ebx
    mov [ebp-16], eax
    mov eax, [ebp+28]
    mov [ebp-20], eax
    mov eax, [ebp-16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else63
    mov eax, [ebp+24]
    mov [ebp-20], eax
    jmp endif62
else63:
endif62:
    mov eax, [ebp+36]
    push eax
    mov eax, [ebp+32]
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+8]
    push eax
    call buf_pixel
    add esp, 24
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-12], eax
    jmp while_start60
while_end61:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start58
while_end59:
draw_char_return:
    mov esp, ebp
    pop ebp
    ret
    
draw_text:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 0
    mov [ebp-4], eax
while_start64:
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+20]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+40]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short66
    test ebx, ebx
    jz and_short66
    mov eax, 1
    jmp and_end67
and_short66:
    xor eax, eax
and_end67:
    test eax, eax
    jz while_end65
    mov eax, [ebp+36]
    push eax
    mov eax, [ebp+32]
    push eax
    mov eax, [ebp+28]
    push eax
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+20]
    add eax, ebx
    movzx eax, byte [eax]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+8]
    push eax
    call draw_char
    add esp, 32
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start64
while_end65:
draw_text_return:
    mov esp, ebp
    pop ebp
    ret
    
create_cursor_bo:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, 64
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp+12]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 64
    push eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp+12]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 32
    push eax
    mov eax, 2
    mov ebx, eax
    mov eax, [ebp+12]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 0
    push eax
    mov eax, 3
    mov ebx, eax
    mov eax, [ebp+12]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp+12]
    push eax
    mov eax, 3223348402
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 54
    push eax
    call syscall3
    add esp, 16
    mov [ebp-4], eax
    mov eax, [ebp-4]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else69
    mov eax, 1
    neg eax
    jmp create_cursor_bo_return
    jmp endif68
else69:
endif68:
    mov eax, 0
    jmp create_cursor_bo_return
create_cursor_bo_return:
    mov esp, ebp
    pop ebp
    ret
    
draw_cursor_to_bo:
    push ebp
    mov ebp, esp
    sub esp, 12
    mov eax, 0
    mov [ebp-4], eax
while_start70:
    mov eax, [ebp-4]
    push eax
    mov eax, 64
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end71
    mov eax, 0
    push eax
    mov eax, [ebp-4]
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start70
while_end71:
    mov eax, 0
    mov [ebp-4], eax
while_start72:
    mov eax, [ebp-4]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end73
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-8], eax
    mov eax, [ebp-4]
    mov [ebp-12], eax
    mov eax, [ebp-12]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short76
    test ebx, ebx
    jz and_short76
    mov eax, 1
    jmp and_end77
and_short76:
    xor eax, eax
and_end77:
    test eax, eax
    jz else75
    mov eax, 4278190080
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    jmp endif74
else75:
endif74:
    mov eax, [ebp-4]
    mov [ebp-8], eax
    mov eax, [ebp-12]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short80
    test ebx, ebx
    jz and_short80
    mov eax, 1
    jmp and_end81
and_short80:
    xor eax, eax
and_end81:
    test eax, eax
    jz else79
    mov eax, 4294967295
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    jmp endif78
else79:
endif78:
    mov eax, [ebp-4]
    push eax
    mov eax, 10
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else83
    mov eax, [ebp-4]
    mov [ebp-8], eax
    mov eax, [ebp-4]
    mov [ebp-12], eax
    mov eax, [ebp-12]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short86
    test ebx, ebx
    jz and_short86
    mov eax, 1
    jmp and_end87
and_short86:
    xor eax, eax
and_end87:
    test eax, eax
    jz else85
    mov eax, 4294967295
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 64
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, [ebp-8]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    jmp endif84
else85:
endif84:
    jmp endif82
else83:
endif82:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start72
while_end73:
draw_cursor_to_bo_return:
    mov esp, ebp
    pop ebp
    ret
    
set_hardware_cursor:
    push ebp
    mov ebp, esp
    sub esp, 8
    mov eax, 0
    mov [ebp-4], eax
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-8]
    mov [ebp-4], eax
    mov eax, 1
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    or eax, ebx
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp+12]
    push eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp+20]
    push eax
    mov eax, 2
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp+24]
    push eax
    mov eax, 3
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 64
    push eax
    mov eax, 4
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 64
    push eax
    mov eax, 5
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp+16]
    push eax
    mov eax, 6
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp-4]
    push eax
    mov eax, 3223086243
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 54
    push eax
    call syscall3
    add esp, 16
set_hardware_cursor_return:
    mov esp, ebp
    pop ebp
    ret
    
move_hardware_cursor:
    push ebp
    mov ebp, esp
    sub esp, 8
    mov eax, 0
    mov [ebp-4], eax
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-8]
    mov [ebp-4], eax
    mov eax, 2
    push eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp+12]
    push eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp+16]
    push eax
    mov eax, 2
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp+20]
    push eax
    mov eax, 3
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 64
    push eax
    mov eax, 4
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 64
    push eax
    mov eax, 5
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, 0
    push eax
    mov eax, 6
    mov ebx, eax
    mov eax, [ebp-4]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
    mov eax, [ebp-4]
    push eax
    mov eax, 3223086243
    push eax
    mov eax, [ebp+8]
    push eax
    mov eax, 54
    push eax
    call syscall3
    add esp, 16
move_hardware_cursor_return:
    mov esp, ebp
    pop ebp
    ret
    
window_ptr:
    push ebp
    mov ebp, esp
    mov eax, [ebp+8]
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, 128
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    add eax, ebx
    jmp window_ptr_return
window_ptr_return:
    mov esp, ebp
    pop ebp
    ret
    
win_get:
    push ebp
    mov ebp, esp
    mov eax, [ebp+12]
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    jmp win_get_return
win_get_return:
    mov esp, ebp
    pop ebp
    ret
    
win_set:
    push ebp
    mov ebp, esp
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp+12]
    mov ebx, eax
    mov eax, [ebp+8]
    shl ebx, 2
    add eax, ebx
    pop ebx
    mov [eax], ebx
win_set_return:
    mov esp, ebp
    pop ebp
    ret
    
get_window_title:
    push ebp
    mov ebp, esp
    mov eax, [ebp+8]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else89
    lea eax, [rel str_0]
    jmp get_window_title_return
    jmp endif88
else89:
endif88:
    mov eax, [ebp+8]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else91
    lea eax, [rel str_1]
    jmp get_window_title_return
    jmp endif90
else91:
endif90:
    mov eax, [ebp+8]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else93
    lea eax, [rel str_2]
    jmp get_window_title_return
    jmp endif92
else93:
endif92:
    lea eax, [rel str_3]
    jmp get_window_title_return
get_window_title_return:
    mov esp, ebp
    pop ebp
    ret
    
create_window:
    push ebp
    mov ebp, esp
    sub esp, 8
    mov eax, 0
    mov [ebp-4], eax
while_start94:
    mov eax, [ebp-4]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end95
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    call window_ptr
    add esp, 8
    mov [ebp-8], eax
    mov eax, 0
    push eax
    mov eax, [ebp-8]
    push eax
    call win_get
    add esp, 8
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    test eax, eax
    jz else97
    mov eax, 1
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp+12]
    push eax
    mov eax, 1
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp+16]
    push eax
    mov eax, 2
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp+20]
    push eax
    mov eax, 3
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp+24]
    push eax
    mov eax, 4
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, 1
    push eax
    mov eax, 5
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, 0
    push eax
    mov eax, 6
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, 0
    push eax
    mov eax, 7
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp+28]
    push eax
    mov eax, 8
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp+32]
    push eax
    mov eax, 9
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp+36]
    push eax
    mov eax, 11
    push eax
    mov eax, [ebp-8]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp-4]
    jmp create_window_return
    jmp endif96
else97:
endif96:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start94
while_end95:
    mov eax, 1
    neg eax
    jmp create_window_return
create_window_return:
    mov esp, ebp
    pop ebp
    ret
    
destroy_window:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, [ebp+12]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+12]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short100
    test ebx, ebx
    jz and_short100
    mov eax, 1
    jmp and_end101
and_short100:
    xor eax, eax
and_end101:
    test eax, eax
    jz else99
    mov eax, [ebp+12]
    push eax
    mov eax, [ebp+8]
    push eax
    call window_ptr
    add esp, 8
    mov [ebp-4], eax
    mov eax, 0
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp-4]
    push eax
    call win_set
    add esp, 12
    jmp endif98
else99:
endif98:
destroy_window_return:
    mov esp, ebp
    pop ebp
    ret
    
draw_decoration:
    push ebp
    mov ebp, esp
    sub esp, 28
    mov eax, 1
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-4], eax
    mov eax, 2
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-8], eax
    mov eax, 3
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-12], eax
    mov eax, 4
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-16], eax
    mov eax, 8
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-20], eax
    mov eax, 6316128
    mov [ebp-24], eax
    mov eax, [ebp+16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else103
    mov eax, 35071
    mov [ebp-24], eax
    mov eax, [ebp-20]
    push eax
    mov eax, 2105376
    mov ebx, eax
    pop eax
    or eax, ebx
    mov [ebp-20], eax
    jmp endif102
else103:
endif102:
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 3
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, 3
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp-16]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 3
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 3
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 24
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 3
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, 11
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    push eax
    call get_window_title
    add esp, 4
    mov [ebp-28], eax
    mov eax, 20
    push eax
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, 16777215
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+8]
    push eax
    call draw_text
    add esp, 36
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, 14500932
    push eax
    mov eax, 16
    push eax
    mov eax, 16
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, 14540100
    push eax
    mov eax, 16
    push eax
    mov eax, 16
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp-12]
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, 16
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
draw_decoration_return:
    mov esp, ebp
    pop ebp
    ret
    
draw_window_body:
    push ebp
    mov ebp, esp
    sub esp, 20
    mov eax, 1
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-4], eax
    mov eax, 2
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-8], eax
    mov eax, 3
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-12], eax
    mov eax, 4
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-16], eax
    mov eax, 9
    push eax
    mov eax, [ebp+12]
    push eax
    call win_get
    add esp, 8
    mov [ebp-20], eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp-20]
    push eax
    mov eax, [ebp-16]
    push eax
    mov eax, 3
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, 24
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 3
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 24
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
draw_window_body_return:
    mov esp, ebp
    pop ebp
    ret
    
composite:
    push ebp
    mov ebp, esp
    sub esp, 12
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+28]
    push eax
    mov eax, [ebp+24]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, 0
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, 0
    mov [ebp-4], eax
while_start104:
    mov eax, [ebp-4]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end105
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+16]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else107
    mov eax, [ebp-4]
    push eax
    mov eax, [ebp+12]
    push eax
    call window_ptr
    add esp, 8
    mov [ebp-8], eax
    mov eax, 0
    push eax
    mov eax, [ebp-8]
    push eax
    call win_get
    add esp, 8
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    push eax
    mov eax, 7
    push eax
    mov eax, [ebp-8]
    push eax
    call win_get
    add esp, 8
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short110
    test ebx, ebx
    jz and_short110
    mov eax, 1
    jmp and_end111
and_short110:
    xor eax, eax
and_end111:
    test eax, eax
    jz else109
    mov eax, 5
    push eax
    mov eax, [ebp-8]
    push eax
    call win_get
    add esp, 8
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else113
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp+8]
    push eax
    call draw_decoration
    add esp, 20
    jmp endif112
else113:
endif112:
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-8]
    push eax
    mov eax, [ebp+8]
    push eax
    call draw_window_body
    add esp, 16
    jmp endif108
else109:
endif108:
    jmp endif106
else107:
endif106:
    mov eax, [ebp-4]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-4], eax
    jmp while_start104
while_end105:
    mov eax, [ebp+16]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short116
    test ebx, ebx
    jz and_short116
    mov eax, 1
    jmp and_end117
and_short116:
    xor eax, eax
and_end117:
    test eax, eax
    jz else115
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp+12]
    push eax
    call window_ptr
    add esp, 8
    mov [ebp-12], eax
    mov eax, 0
    push eax
    mov eax, [ebp-12]
    push eax
    call win_get
    add esp, 8
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    push eax
    mov eax, 7
    push eax
    mov eax, [ebp-12]
    push eax
    call win_get
    add esp, 8
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    sete al
    movzx eax, al
    mov ebx, eax
    pop eax
    test eax, eax
    jz and_short120
    test ebx, ebx
    jz and_short120
    mov eax, 1
    jmp and_end121
and_short120:
    xor eax, eax
and_end121:
    test eax, eax
    jz else119
    mov eax, 5
    push eax
    mov eax, [ebp-12]
    push eax
    call win_get
    add esp, 8
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else123
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, 1
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp+8]
    push eax
    call draw_decoration
    add esp, 20
    jmp endif122
else123:
endif122:
    mov eax, [ebp+24]
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, [ebp+8]
    push eax
    call draw_window_body
    add esp, 16
    jmp endif118
else119:
endif118:
    jmp endif114
else115:
endif114:
composite_return:
    mov esp, ebp
    pop ebp
    ret
    
draw_taskbar:
    push ebp
    mov ebp, esp
    sub esp, 4
    mov eax, [ebp+20]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-4], eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, 2960685
    push eax
    mov eax, 32
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, 5263440
    push eax
    mov eax, 1
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, 26282
    push eax
    mov eax, 32
    push eax
    mov eax, 8
    mov ebx, eax
    pop eax
    sub eax, ebx
    push eax
    mov eax, 80
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 4
    push eax
    mov eax, [ebp+8]
    push eax
    call fill_rect
    add esp, 32
    mov eax, 10
    push eax
    mov eax, [ebp+20]
    push eax
    mov eax, [ebp+16]
    push eax
    mov eax, 26282
    push eax
    mov eax, 16777215
    push eax
    lea eax, [rel str_4]
    push eax
    mov eax, [ebp-4]
    push eax
    mov eax, 12
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 20
    push eax
    mov eax, [ebp+8]
    push eax
    call draw_text
    add esp, 36
draw_taskbar_return:
    mov esp, ebp
    pop ebp
    ret
    
main:
    push ebp
    mov ebp, esp
    sub esp, 148
    mov eax, 420
    push eax
    mov eax, 66
    push eax
    lea eax, [rel str_5]
    push eax
    mov eax, 5
    push eax
    call syscall3
    add esp, 16
    mov [ebp-4], eax
    mov eax, 2
    push eax
    lea eax, [rel str_6]
    push eax
    mov eax, 5
    push eax
    call syscall2
    add esp, 12
    mov [ebp-8], eax
    mov eax, [ebp-8]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else125
    lea eax, [rel str_7]
    push eax
    call print_str
    add esp, 4
    lea eax, [rel str_8]
    push eax
    call print_str
    add esp, 4
    mov eax, 1
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
    jmp endif124
else125:
endif124:
    lea eax, [rel str_9]
    push eax
    call print_str
    add esp, 4
    mov eax, [ebp-8]
    push eax
    call print_num
    add esp, 4
    lea eax, [rel str_10]
    push eax
    call print_str
    add esp, 4
    mov eax, 2
    push eax
    lea eax, [rel str_11]
    push eax
    mov eax, 5
    push eax
    call syscall2
    add esp, 12
    mov [ebp-12], eax
    mov eax, [ebp-12]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else127
    lea eax, [rel str_12]
    push eax
    call print_str
    add esp, 4
    mov eax, 1
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
    jmp endif126
else127:
endif126:
    mov eax, 0
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov [ebp-16], eax
    mov eax, [ebp-16]
    push eax
    mov eax, 8192
    mov ebx, eax
    pop eax
    add eax, ebx
    push eax
    mov eax, 45
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-16]
    mov [ebp-20], eax
    mov eax, [ebp-16]
    push eax
    mov eax, 256
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-24], eax
    mov eax, [ebp-16]
    push eax
    mov eax, 512
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-28], eax
    mov eax, [ebp-16]
    push eax
    mov eax, 4096
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-32], eax
    mov eax, 17920
    mov [ebp-36], eax
    mov eax, [ebp-20]
    push eax
    mov eax, [ebp-36]
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 54
    push eax
    call syscall3
    add esp, 16
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-20]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    mov [ebp-40], eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-20]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    mov [ebp-44], eax
    lea eax, [rel str_13]
    push eax
    call print_str
    add esp, 4
    mov eax, [ebp-40]
    push eax
    call print_num
    add esp, 4
    lea eax, [rel str_14]
    push eax
    call print_str
    add esp, 4
    mov eax, [ebp-44]
    push eax
    call print_num
    add esp, 4
    lea eax, [rel str_15]
    push eax
    call print_str
    add esp, 4
    mov eax, [ebp-32]
    push eax
    mov eax, [ebp-8]
    push eax
    call create_cursor_bo
    add esp, 8
    mov [ebp-48], eax
    mov eax, 0
    mov [ebp-52], eax
    mov eax, 0
    mov [ebp-56], eax
    mov eax, 0
    mov [ebp-60], eax
    mov eax, [ebp-48]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else129
    mov eax, 3
    mov ebx, eax
    mov eax, [ebp-32]
    shl ebx, 2
    add eax, ebx
    mov eax, [eax]
    mov [ebp-56], eax
    mov eax, 41
    mov [ebp-60], eax
    mov eax, 1
    mov [ebp-52], eax
    jmp endif128
else129:
endif128:
    mov eax, 2
    push eax
    lea eax, [rel str_16]
    push eax
    mov eax, 5
    push eax
    call syscall2
    add esp, 12
    mov [ebp-64], eax
    mov eax, [ebp-64]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else131
    mov eax, 1
    push eax
    mov eax, 19258
    push eax
    mov eax, [ebp-64]
    push eax
    mov eax, 54
    push eax
    call syscall3
    add esp, 16
    jmp endif130
else131:
endif130:
    mov eax, [ebp-40]
    push eax
    mov eax, [ebp-44]
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    imul eax, ebx
    mov [ebp-68], eax
    mov eax, 0
    push eax
    mov eax, [ebp-12]
    push eax
    mov eax, 1
    push eax
    mov eax, 1
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    or eax, ebx
    push eax
    mov eax, [ebp-68]
    push eax
    mov eax, 0
    push eax
    mov eax, 192
    push eax
    call syscall6
    add esp, 28
    mov [ebp-72], eax
    mov eax, 0
    mov [ebp-76], eax
    mov eax, [ebp-72]
    mov [ebp-80], eax
    mov eax, [ebp-80]
    push eax
    mov eax, 4294963200
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else133
    mov eax, [ebp-72]
    mov [ebp-76], eax
    jmp endif132
else133:
    mov eax, [ebp-64]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else135
    mov eax, 0
    push eax
    mov eax, 19258
    push eax
    mov eax, [ebp-64]
    push eax
    mov eax, 54
    push eax
    call syscall3
    add esp, 16
    jmp endif134
else135:
endif134:
    mov eax, 1
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
endif132:
    mov eax, 2
    push eax
    lea eax, [rel str_17]
    push eax
    mov eax, 5
    push eax
    call syscall2
    add esp, 12
    mov [ebp-84], eax
    mov eax, [ebp-84]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else137
    mov eax, 1
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
    jmp endif136
else137:
endif136:
    mov eax, 3
    push eax
    mov eax, [ebp-84]
    push eax
    mov eax, 55
    push eax
    call syscall2
    add esp, 12
    mov [ebp-88], eax
    mov eax, [ebp-88]
    push eax
    mov eax, 2048
    mov ebx, eax
    pop eax
    or eax, ebx
    push eax
    mov eax, 4
    push eax
    mov eax, [ebp-84]
    push eax
    mov eax, 55
    push eax
    call syscall3
    add esp, 16
    mov eax, 0
    mov [ebp-92], eax
while_start138:
    mov eax, [ebp-92]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz while_end139
    mov eax, [ebp-92]
    push eax
    mov eax, [ebp-28]
    push eax
    call window_ptr
    add esp, 8
    mov [ebp-96], eax
    mov eax, 0
    push eax
    mov eax, 0
    push eax
    mov eax, [ebp-96]
    push eax
    call win_set
    add esp, 12
    mov eax, [ebp-92]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-92], eax
    jmp while_start138
while_end139:
    mov eax, 1
    push eax
    mov eax, 15263976
    push eax
    mov eax, 2250154
    push eax
    mov eax, 250
    push eax
    mov eax, 350
    push eax
    mov eax, 60
    push eax
    mov eax, 80
    push eax
    mov eax, [ebp-28]
    push eax
    call create_window
    add esp, 32
    mov eax, 2
    push eax
    mov eax, 15790320
    push eax
    mov eax, 2271829
    push eax
    mov eax, 280
    push eax
    mov eax, 380
    push eax
    mov eax, 140
    push eax
    mov eax, 250
    push eax
    mov eax, [ebp-28]
    push eax
    call create_window
    add esp, 32
    mov eax, 3
    push eax
    mov eax, 15658734
    push eax
    mov eax, 11162914
    push eax
    mov eax, 240
    push eax
    mov eax, 320
    push eax
    mov eax, 100
    push eax
    mov eax, 450
    push eax
    mov eax, [ebp-28]
    push eax
    call create_window
    add esp, 32
    mov [ebp-100], eax
    mov eax, [ebp-40]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov [ebp-104], eax
    mov eax, [ebp-44]
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    xor edx, edx
    idiv ebx
    mov [ebp-108], eax
    mov eax, 1718874
    mov [ebp-112], eax
    mov eax, [ebp-100]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else141
    mov eax, [ebp-100]
    push eax
    mov eax, [ebp-28]
    push eax
    call window_ptr
    add esp, 8
    mov [ebp-116], eax
    mov eax, 1
    push eax
    mov eax, 6
    push eax
    mov eax, [ebp-116]
    push eax
    call win_set
    add esp, 12
    jmp endif140
else141:
endif140:
    mov eax, [ebp-112]
    push eax
    mov eax, [ebp-44]
    push eax
    mov eax, [ebp-40]
    push eax
    mov eax, [ebp-100]
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, [ebp-76]
    push eax
    call composite
    add esp, 24
    mov eax, [ebp-44]
    push eax
    mov eax, [ebp-40]
    push eax
    mov eax, [ebp-28]
    push eax
    mov eax, [ebp-76]
    push eax
    call draw_taskbar
    add esp, 16
    mov eax, [ebp-52]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else143
    mov eax, [ebp-108]
    push eax
    mov eax, [ebp-104]
    push eax
    mov eax, [ebp-56]
    push eax
    mov eax, [ebp-60]
    push eax
    mov eax, [ebp-8]
    push eax
    call set_hardware_cursor
    add esp, 20
    jmp endif142
else143:
endif142:
    mov eax, 1
    mov [ebp-120], eax
while_start144:
    mov eax, [ebp-120]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz while_end145
    mov eax, 0
    mov [ebp-124], eax
    mov eax, 0
    mov [ebp-128], eax
    mov eax, 0
    mov [ebp-132], eax
    mov eax, 4
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, [ebp-84]
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-136], eax
while_start146:
    mov eax, [ebp-136]
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz while_end147
    mov eax, 1
    mov [ebp-132], eax
    mov eax, 0
    mov ebx, eax
    mov eax, [ebp-24]
    add eax, ebx
    movzx eax, byte [eax]
    mov [ebp-140], eax
    mov eax, 1
    mov ebx, eax
    mov eax, [ebp-24]
    add eax, ebx
    movzx eax, byte [eax]
    mov [ebp-144], eax
    mov eax, 2
    mov ebx, eax
    mov eax, [ebp-24]
    add eax, ebx
    movzx eax, byte [eax]
    mov [ebp-148], eax
    mov eax, [ebp-140]
    push eax
    mov eax, 16
    mov ebx, eax
    pop eax
    and eax, ebx
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else149
    mov eax, [ebp-144]
    push eax
    mov eax, 256
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-144], eax
    jmp endif148
else149:
endif148:
    mov eax, [ebp-140]
    push eax
    mov eax, 32
    mov ebx, eax
    pop eax
    and eax, ebx
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else151
    mov eax, [ebp-148]
    push eax
    mov eax, 256
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-148], eax
    jmp endif150
else151:
endif150:
    mov eax, [ebp-124]
    push eax
    mov eax, [ebp-144]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-124], eax
    mov eax, [ebp-128]
    push eax
    mov eax, [ebp-148]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-128], eax
    mov eax, 4
    push eax
    mov eax, [ebp-24]
    push eax
    mov eax, [ebp-84]
    push eax
    mov eax, 3
    push eax
    call syscall3
    add esp, 16
    mov [ebp-136], eax
    jmp while_start146
while_end147:
    mov eax, [ebp-132]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else153
    mov eax, [ebp-104]
    push eax
    mov eax, [ebp-124]
    mov ebx, eax
    pop eax
    add eax, ebx
    mov [ebp-104], eax
    mov eax, [ebp-108]
    push eax
    mov eax, [ebp-128]
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-108], eax
    mov eax, [ebp-104]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else155
    mov eax, 0
    mov [ebp-104], eax
    jmp endif154
else155:
endif154:
    mov eax, [ebp-104]
    push eax
    mov eax, [ebp-40]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else157
    mov eax, [ebp-40]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-104], eax
    jmp endif156
else157:
endif156:
    mov eax, [ebp-108]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setl al
    movzx eax, al
    test eax, eax
    jz else159
    mov eax, 0
    mov [ebp-108], eax
    jmp endif158
else159:
endif158:
    mov eax, [ebp-108]
    push eax
    mov eax, [ebp-44]
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else161
    mov eax, [ebp-44]
    push eax
    mov eax, 1
    mov ebx, eax
    pop eax
    sub eax, ebx
    mov [ebp-108], eax
    jmp endif160
else161:
endif160:
    mov eax, [ebp-52]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setne al
    movzx eax, al
    test eax, eax
    jz else163
    mov eax, [ebp-108]
    push eax
    mov eax, [ebp-104]
    push eax
    mov eax, [ebp-60]
    push eax
    mov eax, [ebp-8]
    push eax
    call move_hardware_cursor
    add esp, 16
    jmp endif162
else163:
endif162:
    jmp endif152
else153:
endif152:
    jmp while_start144
while_end145:
    mov eax, [ebp-64]
    push eax
    mov eax, 0
    mov ebx, eax
    pop eax
    cmp eax, ebx
    setge al
    movzx eax, al
    test eax, eax
    jz else165
    mov eax, 0
    push eax
    mov eax, 19258
    push eax
    mov eax, [ebp-64]
    push eax
    mov eax, 54
    push eax
    call syscall3
    add esp, 16
    mov eax, [ebp-64]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
    jmp endif164
else165:
endif164:
    mov eax, [ebp-8]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-12]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
    mov eax, [ebp-84]
    push eax
    mov eax, 6
    push eax
    call syscall1
    add esp, 8
    mov eax, 0
    push eax
    mov eax, 1
    push eax
    call syscall1
    add esp, 8
main_return:
    mov esp, ebp
    pop ebp
    ret